# -*- coding: utf-8 -*-
"""Historias de aprendiz (urna) y acceso de gestión. IDs originales conservados."""


from _excel_senior_helpers import ca, cp


HU_APRENDIZ = [
    {
        "id": "HU-SIG-001-AP",
        "sheet": "HU-001-AP",
        "titulo": "Iniciar sesión como Aprendiz",
        "como": "Aprendiz",
        "quiero": "entrar a la urna con el correo y la contraseña que están en el censo",
        "para": "ver solo las votaciones de mi centro y jornada, sin el menú de gestión",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-01 Identidad",
        "epica": "EP-SIG-001",
        "epica_nom": "Accesos",
        "feature": "FT-SIG-001",
        "feature_nom": "Acceso a la urna",
        "rf": "RF-NU-001",
        "cu": "CU-01",
        "journey": "J-02 paso 1",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin puerta de urna no hay voto. Es el primer paso del journey del votante.",
        "sp": 5,
        "sp_why": "Autenticación bcrypt + error genérico + no filtrar menú de gestión + devolver centro y jornada. No incluye JWT.",
        "rank": 7,
        "fase": "A — Cimientos",
        "mvp": "Sí",
        "valor": "Separa la urna de la mesa. Entrega circunscripción (centro + jornada del grupo) para filtrar la urna.",
        "problema": "Hoy, sin sistema, cualquiera entra a un link o a un grupo y vota 'por el compañero'. El censo no es la llave.",
        "exito": "Un aprendiz del padrón entra; un extraño no; un gestor no usa esta puerta; la respuesta no trae contraseña; la urna sabe centro y jornada.",
        "in_scope": [
            "Formulario de urna: correo + contraseña",
            "Verificación bcrypt contra el censo",
            "Respuesta con identificador, centro y jornada (jornada sale del grupo)",
            "Mensaje genérico si falla la autenticación (no revelar si el correo existe)",
            "Campos incompletos no se envían / no autentican",
            "El menú de la urna no muestra opciones de Funcionario ni Administrador",
            "Error de servidor no autentica",
        ],
        "out_scope": [
            "Login de gestión (eso es HU-010)",
            "JWT / sesión de API (deuda técnica, no esta HU)",
            "Recuperar o cambiar contraseña (existe un PUT huérfano; no hay HU de producto)",
            "Cerrar sesión (hueco de journey; no hay HU)",
            "Mensaje distinto para aprendiz cancelado vs clave mala (pregunta abierta; hasta que el PO cierre, el error es genérico)",
        ],
        "pre": "El aprendiz existe en el censo (HU-012, HU-023 o HU-024). Tiene correo y contraseña. El grupo tiene jornada.",
        "post": "Queda autenticado como Aprendiz. El cliente tiene centro y jornada. No hay token de API en el as-is. No se devolvió la contraseña ni el hash.",
        "trigger": "Envía correo y contraseña en la puerta pública de la urna.",
        "permisos_si": "Solo perfil Aprendiz.",
        "permisos_no": "Funcionario y Administrador no usan esta puerta. El aprendiz no ve gestión.",
        "entidades": "Aprendiz, Grupo (jornada), CentroFormacion, Perfil",
        "campos": "correo (obligatorio, formato email) · contraseña (obligatorio, no se relee) · salida: id aprendiz, id centro, jornada, nombres. NUNCA password ni hash.",
        "rn": "RN-SIG-008, RN-SIG-013",
        "rnf": "RNF-NU-001, RNF-NU-004",
        "deps": "Censo cargado (HU-012 o HU-023/024). No depende de JWT.",
        "bloquea": "HU-002 a HU-007",
        "dueno": "Alex · acepta Sofia (seguridad de mensaje genérico)",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Ninguna de negocio para el camino feliz. Pendiente de PO: ¿un aprendiz no habilitado ve el mismo error genérico al entrar?",
        "invest": "I sí (no es JWT) · N sí (actor real) · V sí (abre la urna) · E sí (SP 5) · S sí · T sí (CA verificables)",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Probar que correo inventado y clave mala producen el MISMO tipo de error. Inspeccionar el JSON: cero rastros de password. Un funcionario no entra por esta URL con éxito de urna.",
        "notas_dev": "Contrato actual: POST /api/aprendiz/login. Objetivo = estos CA. El PUT de contraseña no forma parte de esta historia.",
        "preguntas": "¿El aprendiz cancelado/retirado recibe el mismo error genérico? (P12). No se inventa un mensaje especial.",
        "tareas": "BE: validar contrato vs CA · FE: formulario urna, sin menú de mesa · BD: no exponer hash · Test: CP-001-*",
        "ca": [
            ca("CA-01", "Feliz",
               "un aprendiz del censo con correo y contraseña válidos",
               "envía ambos campos por la puerta de urna",
               "el sistema autentica con bcrypt, no devuelve la contraseña ni el hash, y entrega identificador, centro de formación y jornada del grupo"),
            ca("CA-02", "Validación",
               "el formulario de urna visible",
               "falta el correo o falta la contraseña",
               "no autentica e indica que los campos son obligatorios"),
            ca("CA-03", "Seguridad",
               "un correo que no está en el censo, o un correo que sí está con contraseña incorrecta",
               "intenta entrar",
               "el sistema responde el mismo tipo de error genérico y no revela si el correo existe"),
            ca("CA-04", "Permiso",
               "un aprendiz ya autenticado",
               "consulta su menú / navegación",
               "no ve opciones de Funcionario ni de Administrador"),
            ca("CA-05", "Error",
               "un fallo interno (por ejemplo, base de datos caída)",
               "corre el login",
               "responde error de servidor y no deja sesión de urna"),
            ca("CA-06", "Permiso",
               "credenciales de un Funcionario o Administrador",
               "se envían a la puerta de urna",
               "no se abre la urna de aprendiz (esta puerta no es la de gestión)"),
        ],
        "ca_cond": [
            ca("CA-P12", "Condicionado — no implementar un mensaje especial",
               "un aprendiz del censo en estado cancelado o retirado",
               "intenta iniciar sesión",
               "hasta que el PO cierre P12, el comportamiento documentado es el error genérico de CA-03. No se diseña un mensaje que delate el estado."),
        ],
        "cp": [
            cp("CP-001-01", "CA-01", "Login válido", "200/éxito; body sin password; hay centro y jornada"),
            cp("CP-001-02", "CA-02", "Sin correo", "No autentica; aviso de obligatorio", "Validación"),
            cp("CP-001-03", "CA-02", "Sin contraseña", "No autentica; aviso de obligatorio", "Validación"),
            cp("CP-001-04", "CA-03", "Correo inventado", "Error genérico, mismo tipo que clave mala", "Seguridad"),
            cp("CP-001-05", "CA-03", "Clave incorrecta de un correo real", "Mismo tipo de error que CP-001-04", "Seguridad"),
            cp("CP-001-06", "CA-04", "Menú del aprendiz", "Cero ítems de gestión", "Permiso"),
            cp("CP-001-07", "CA-05", "Forzar error de BD", "Error de servidor; no sesión", "Error"),
            cp("CP-001-08", "CA-06", "Credencial de funcionario en puerta urna", "No abre urna", "Permiso"),
        ],
        "riesgo": "Medio — si el error deja de ser genérico, se enumera el censo.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-002-AP",
        "sheet": "HU-002-AP",
        "titulo": "Consultar votaciones de mi circunscripción",
        "como": "Aprendiz autenticado",
        "quiero": "ver las elecciones de MI centro y MI jornada que están abiertas ahora",
        "para": "encontrar solo la urna que me corresponde y no la de otra sede u otro turno",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-007",
        "feature_nom": "Urna filtrada",
        "rf": "RF-NU-002",
        "cu": "CU-02",
        "journey": "J-02 paso 2",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin filtro de circunscripción un aprendiz votaría en otra mesa. Invariantes 3 y 4.",
        "sp": 5,
        "sp_why": "Tres predicados a la vez: centro + jornada + ahora dentro de fecha y hora. Lista vacía no es error.",
        "rank": 8,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Hace real la circunscripción. El votante no explora el sistema: ve lo suyo o no ve nada.",
        "problema": "En papel, el padrón de otra ficha se cuela. En digital, un listado 'todas las activas del país' es el mismo error.",
        "exito": "La lista contiene únicamente elecciones del centro del aprendiz, de su jornada (Mañana/Tarde/Noche) y con fecha-hora actual entre inicio y fin. Vacío = vacío, no 404.",
        "in_scope": [
            "Listado filtrado por centro del aprendiz, jornada del grupo y ventana completa (fecha Y hora)",
            "Lista vacía como resultado válido",
            "Excluir otras sedes, otras jornadas, aún no abre, ya cerró",
        ],
        "out_scope": [
            "Ver elecciones cerradas (eso es HU-015, del funcionario)",
            "Ver totales o ganador",
            "Elegir otro centro",
            "El código as-is que solo mira fecha_fin >= hoy: eso es un defecto a alinear, no el requisito",
        ],
        "pre": "Aprendiz autenticado (HU-001) con centro y jornada en sesión.",
        "post": "El aprendiz tiene (0..n) elecciones votables ahora. Ninguna fuera de circunscripción o ventana.",
        "trigger": "Entra a 'mis votaciones' / pide el listado activo de urna.",
        "permisos_si": "Aprendiz autenticado, sobre su propio centro/jornada.",
        "permisos_no": "Funcionario y Administrador no votan. El aprendiz no lista la red.",
        "entidades": "Eleccion, CentroFormacion, Grupo.jornada",
        "campos": "Filtros de sistema (no los elige el usuario): idcentro, jornada, ahora. Salida: id elección, nombre, jornada, inicio, fin. Sin totales.",
        "rn": "RN-SIG-004, RN-SIG-005",
        "rnf": "RNF-NU-002, RNF-NU-003",
        "deps": "HU-SIG-001-AP",
        "bloquea": "HU-003, HU-004",
        "dueno": "Alex",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Ninguna de negocio. Hay desalineación de código (ver notas_dev).",
        "invest": "Cumple. Independiente salvo identidad.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Reloj: usar una elección que abre en 1 minuto y una que cerró hace 1 minuto. Cruzar centro A vs B y jornada Mañana vs Tarde con el mismo aprendiz.",
        "notas_dev": "Hallazgo as-is: eleccionesAactivas() filtra débil (fecha_fin >= hoy). El requisito objetivo es ESTE CA, no el código. Alinear en desarrollo futuro.",
        "preguntas": "Ninguna de negocio para el filtro. El reloj de urna debe ser el mismo en listado, OTP y voto.",
        "tareas": "BE: listado centro+jornada+ventana completa · FE: lista y estado vacío · Test: CP-002-*",
        "ca": [
            ca("CA-01", "Feliz",
               "un aprendiz autenticado con centro C y jornada J, y una elección de C+J con ahora dentro de inicio y fin",
               "pide votaciones activas",
               "esa elección aparece y ninguna otra"),
            ca("CA-02", "Vacío",
               "ninguna elección cumple centro + jornada + ventana",
               "consulta",
               "recibe lista vacía, no un error"),
            ca("CA-03", "Permiso",
               "existen elecciones de otro centro o de otra jornada",
               "consulta",
               "no aparecen"),
            ca("CA-04", "Borde",
               "ahora es anterior al inicio (fecha o hora) de una elección de su circunscripción",
               "consulta",
               "esa elección no aparece"),
            ca("CA-05", "Borde",
               "ahora es posterior al fin (fecha o hora) de una elección de su circunscripción",
               "consulta",
               "esa elección no aparece"),
            ca("CA-06", "Seguridad",
               "un aprendiz no autenticado",
               "pide el listado",
               "no obtiene elecciones de nadie"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-002-01", "CA-01", "Centro + jornada + ahora dentro", "Aparece solo esa"),
            cp("CP-002-02", "CA-02", "Ninguna coincide", "Lista vacía 200", "Vacío"),
            cp("CP-002-03", "CA-03", "Otra sede", "No aparece", "Permiso"),
            cp("CP-002-04", "CA-03", "Otra jornada", "No aparece", "Permiso"),
            cp("CP-002-05", "CA-04", "Aún no abre (hora)", "No aparece", "Borde"),
            cp("CP-002-06", "CA-05", "Ya cerró (hora)", "No aparece", "Borde"),
            cp("CP-002-07", "CA-06", "Sin autenticación", "Rechazo", "Seguridad"),
        ],
        "riesgo": "Alto si el filtro de hora queda a medias: urna eterna o urna a destiempo.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-003-AP",
        "sheet": "HU-003-AP",
        "titulo": "Ver el tarjetón de una elección",
        "como": "Aprendiz autenticado",
        "quiero": "ver nombre, número, propuesta y foto (si hay) de cada candidato de ESA elección",
        "para": "elegir con información suficiente, sin un orden que privilegie a nadie y sin ver quién va ganando",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-008",
        "feature_nom": "Consulta de tarjetón",
        "rf": "RF-NU-003",
        "cu": "CU-03",
        "journey": "J-02 paso 3",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin tarjetón identificable la urna es un combo de nombres. El secreto de escrutinio empieza aquí: cero totales.",
        "sp": 3,
        "sp_why": "Consulta acotada + shuffle + no llamar reporte. Foto ausente no rompe.",
        "rank": 9,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Tarjetón serio: persona del censo, número, propuesta, foto opcional. Orden no privilegiado.",
        "problema": "Una lista ordenada por quien se inscribió primero o por votos es un ranking, no un tarjetón.",
        "exito": "Solo candidatos de esa elección; campos visibles; sin totales; orden no estable de administración; foto faltante no cae la pantalla.",
        "in_scope": [
            "Candidatos de la elección abierta desde HU-002",
            "Nombre, número de tarjetón, propuesta, foto si existe",
            "Orden no privilegiado (aleatorio / desordenado)",
            "Cero totales, cero ganador, cero acta",
            "Rechazo si la elección no es de su circunscripción",
        ],
        "out_scope": [
            "Inscribir candidatos (HU-016)",
            "Votar (HU-006)",
            "Mostrar resultados al cierre (no hay HU; el aprendiz no ve resultados en este producto)",
        ],
        "pre": "HU-001 y HU-002. La elección tiene al menos un candidato (HU-016). La elección está en su lista activa.",
        "post": "El aprendiz ve el tarjetón. No se registró voto. No se filtró un ranking.",
        "trigger": "Abre una elección de su listado.",
        "permisos_si": "Aprendiz, solo elecciones de su circunscripción en ventana.",
        "permisos_no": "No ve tarjetón de otra sede. Funcionario no usa esta pantalla de votante.",
        "entidades": "Candidato, Aprendiz, Eleccion",
        "campos": "nombre y apellidos del aprendiz candidato · numero_tarjeton · propuesta · foto (URL opcional). PROHIBIDO: conteo de votos, ganador.",
        "rn": "RN-SIG-007, RN-SIG-011, RN-SIG-022",
        "rnf": "RNF-NU-003, RNF-NU-004",
        "deps": "HU-002-AP · HU-016-FU",
        "bloquea": "HU-006",
        "dueno": "Alex",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Ninguna de negocio. Diseño visual del tarjetón no está en el repo de API (DoR 12).",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Dos cargas seguidas no deben reproducir un orden fijo de administración. Un candidato de la elección B no aparece en A. Mock sin foto.",
        "notas_dev": "BE: listar por ideleccion + RANDOM(). FE: no llamar GET reporte. Foto ausente = placeholder, no 500.",
        "preguntas": "Ninguna de negocio sobre el contenido mínimo.",
        "tareas": "BE listar + shuffle · FE tarjetón · Test CP-003-*",
        "ca": [
            ca("CA-01", "Feliz",
               "el aprendiz abre una elección que está en su listado y tiene candidatos",
               "pide el tarjetón",
               "ve únicamente candidatos de esa elección, cada uno con nombre, número, propuesta y foto si existe"),
            ca("CA-02", "Feliz",
               "el tarjetón se muestra",
               "se observa el orden",
               "el orden no es un ranking administrativo (no favorece al primero inscrito ni a quien va ganando)"),
            ca("CA-03", "Seguridad",
               "el tarjetón visible",
               "el aprendiz busca totales, ganador o acta",
               "no hay totales, no hay ganador, no hay enlace al reporte"),
            ca("CA-04", "Permiso",
               "una elección que no es de su centro o jornada, o a la que no llegó por HU-002",
               "intenta abrir el tarjetón",
               "el sistema no se la sirve como urna"),
            ca("CA-05", "Borde",
               "un candidato sin foto",
               "se renderiza el tarjetón",
               "la tarjeta se muestra igual (nombre, número, propuesta); la ausencia de foto no rompe la pantalla"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-003-01", "CA-01", "Tarjetón completo", "Campos visibles, solo esa elección"),
            cp("CP-003-02", "CA-02", "Dos recargas", "Orden no privilegiado / no fijo de admin"),
            cp("CP-003-03", "CA-03", "Inspección de UI y red", "Cero llamadas a reporte; cero totales"),
            cp("CP-003-04", "CA-04", "Elección de otro centro", "No se sirve", "Permiso"),
            cp("CP-003-05", "CA-05", "Foto ausente", "No 500; tarjeta usable", "Borde"),
        ],
        "riesgo": "Bajo. Riesgo de producto si alguien pinta un ranking 'por nombre'.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-004-AP",
        "sheet": "HU-004-AP",
        "titulo": "Solicitar código OTP al correo del censo",
        "como": "Aprendiz autenticado en una elección de su circunscripción",
        "quiero": "pedir un código al correo que está en el padrón",
        "para": "demostrar que tengo ese buzón SIN que eso registre un voto",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-009",
        "feature_nom": "Verificación de buzón (OTP)",
        "rf": "RF-NU-004",
        "cu": "CU-04",
        "journey": "J-02 paso 4",
        "moscow": "MUST HAVE",
        "moscow_why": "Es la prueba de buzón. Sin ella el voto remoto no se distingue de 'me prestaron la clave'. Validar ≠ votar empieza aquí.",
        "sp": 8,
        "sp_why": "Generación, caducidad, SMTP, no crear voto, no devolver OTP en prod, rechazos de estado/centro/ya votó, fallo de correo limpio.",
        "rank": 10,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Prueba de posesión del correo del censo. Invariante 2. RNF-005: SMTP caído no deja voto.",
        "problema": "Confiar ciegamente en quien conoce la contraseña del compañero.",
        "exito": "Se envía un código de 6 caracteres al correo del padrón, caduca (default 5 min / OTP_EXPIRATION_MINUTES), no se inserta voto, en producción no viaja en el JSON, y si SMTP falla no hay voto fantasma.",
        "in_scope": [
            "Generar OTP de 6 caracteres",
            "Enviar al correo del censo (no a un correo tecleado ahora)",
            "Caducidad configurable por entorno (default documentado: 5 minutos)",
            "NO crear fila en votos",
            "NO devolver el código en producción",
            "Rechazar: ya votó, otro centro, estado no habilitado, aprendiz inexistente",
            "Fallo SMTP: no queda voto",
            "Ventana oficial: fuera de fecha/hora no se genera (RNF-002; hoy el check está comentado en código — el requisito manda restaurarlo)",
        ],
        "out_scope": [
            "Validar el código (HU-005)",
            "Registrar el voto (HU-006)",
            "Límite de reenvíos (no definido; no se inventa un tope)",
            "OTP por SMS",
            "Cambiar el correo en este paso",
        ],
        "pre": "HU-001, HU-002. Aprendiz en circunscripción. Elección en ventana. SMTP configurado. No existe voto previo de ese aprendiz en esa elección.",
        "post": "Existe un OTP vigente asociado a aprendiz+elección. Cero filas nuevas en votos. El aprendiz todavía no ha votado.",
        "trigger": "Pulsa 'enviar código' / solicita OTP para esa elección.",
        "permisos_si": "Aprendiz, su elección, su centro.",
        "permisos_no": "Funcionario no pide OTP. Un aprendiz no pide OTP de otra sede.",
        "entidades": "ValidacionVoto, Aprendiz, Eleccion",
        "campos": "codigo (6, no en JSON prod) · aprendiz_id · elecciones_id · expiración. Estados de padrón que el CÓDIGO trata como habilitados: activo, en formacion, suspension, pendiente, condicionado. Cancelado/retirado no.",
        "rn": "RN-SIG-002, RN-SIG-003, RN-SIG-014, RN-SIG-015, RN-SIG-021 (esta última pendiente de validación de negocio)",
        "rnf": "RNF-NU-001, RNF-NU-002, RNF-NU-005",
        "deps": "HU-001, HU-002, SMTP",
        "bloquea": "HU-005",
        "dueno": "Alex · Sofia revisa OTP",
        "dor": "Parcial — reenvíos no definidos; RN-021 no validada por negocio",
        "dor_gap": "P6 reenvíos/intentos. P7 estados suspension/pendiente/condicionado. P16 reutilizar OTP si cierra el navegador. P17 copy si SMTP falla. P18 ¿5 min es negocio o default técnico?",
        "invest": "Cumple si NO se fusiona con 005 ni 006. Valiosa y testeable. Estimable 8.",
        "invest_ok": "Cumple INVEST (no fusionar)",
        "notas_qa": "Interceptar respuesta en un entorno tipo prod: el código NO va en el body. Mock SMTP down: cero votos. Pedir OTP no debe crear votoxcandidato.",
        "notas_dev": "POST /api/validaciones/generarOtp. Restaurar validación de ventana (hoy comentada). No devolver OTP en prod. Estados: documentar as-is y marcar RN-021 como pendiente de PO.",
        "preguntas": "P6 reenvíos · P7 ¿suspensión/pendiente/condicionado votan? · P16 OTP y cierre de navegador · P17 copy SMTP · P18 ¿5 min es RN?",
        "tareas": "BE generarOtp + mail · no OTP en prod · restaurar ventana · test SMTP mock",
        "ca": [
            ca("CA-01", "Feliz",
               "aprendiz habilitado, mismo centro, elección en ventana, sin voto VOTED_",
               "solicita OTP",
               "se genera un código de 6 caracteres, caduca según entorno (default 5 min) y se envía al correo del censo"),
            ca("CA-02", "Feliz",
               "la solicitud de OTP acaba de correr",
               "se inspecciona la tabla de votos",
               "no existe una fila nueva de voto"),
            ca("CA-03", "Seguridad",
               "el entorno es producción",
               "la API responde la solicitud de OTP",
               "el cuerpo NO incluye el código"),
            ca("CA-04", "Excepción",
               "el aprendiz ya votó en esa elección, o no es de ese centro, o no existe, o su estado no está en la lista habilitada",
               "pide OTP",
               "el sistema rechaza y no envía código útil"),
            ca("CA-05", "Error",
               "SMTP no puede entregar",
               "se pidió OTP",
               "no queda un voto registrado (RNF-NU-005)"),
            ca("CA-06", "Borde",
               "ahora está fuera de la ventana de la elección",
               "pide OTP",
               "se rechaza (invariante 4). El código as-is tiene este check comentado: el requisito es rechazar."),
        ],
        "ca_cond": [
            ca("CA-P06", "Condicionado",
               "el aprendiz pide el código varias veces",
               "reenvía",
               "NO HAY tope escrito. No implementar un 'máximo 3' hasta que el PO cierre P6."),
            ca("CA-P07", "Condicionado",
               "aprendiz en suspension / pendiente / condicionado",
               "pide OTP",
               "el CÓDIGO actual lo permite. No afirmar que es la norma SENA hasta que el PO cierre RN-021."),
        ],
        "cp": [
            cp("CP-004-01", "CA-01", "Envío feliz", "Correo sale; código 6 chars; hay expiración"),
            cp("CP-004-02", "CA-02", "Inspección BD votos", "Cero inserts de voto"),
            cp("CP-004-03", "CA-03", "Response prod", "Sin campo codigo", "Seguridad"),
            cp("CP-004-04", "CA-04", "Ya votó", "Rechazo", "Excepción"),
            cp("CP-004-05", "CA-04", "Otro centro", "Rechazo", "Excepción"),
            cp("CP-004-06", "CA-04", "Estado no listado (cancelado)", "Rechazo", "Excepción"),
            cp("CP-004-07", "CA-05", "SMTP caído", "Cero votos", "Error"),
            cp("CP-004-08", "CA-06", "Fuera de ventana", "Rechazo OTP", "Borde"),
        ],
        "riesgo": "Alto — núcleo de integridad. SMTP y exposición del código son fallos de elección, no de UX.",
        "estado": "Especificada · DoR parcial",
    },
    {
        "id": "HU-SIG-005-AP",
        "sheet": "HU-005-AP",
        "titulo": "Validar el código OTP (sin votar)",
        "como": "Aprendiz que ya recibió el código",
        "quiero": "validar el código de 6 caracteres",
        "para": "habilitar el paso de votar SIN depositar el voto",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-009",
        "feature_nom": "Verificación de buzón (OTP)",
        "rf": "RF-NU-005",
        "cu": "CU-05",
        "journey": "J-02 paso 5",
        "moscow": "MUST HAVE",
        "moscow_why": "Si validar insertara el voto, el aprendiz votaría al teclear el correo. Invariante 2.",
        "sp": 5,
        "sp_why": "Validación de vigencia, uso único, longitud 6, y la prueba explícita de que no toca votoxcandidato.",
        "rank": 11,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Separa 'tengo el buzón' de 'ya voté'. Permite el paso HU-006 sin adelantarlo.",
        "problema": "Sistemas mal diseñados cuentan el OTP como sufragio. Eso no es urna.",
        "exito": "Código vigente de 6 caracteres se acepta y no hay insert de voto. Usado, vencido, inventado o de otra longitud se rechazan.",
        "in_scope": [
            "Aceptar código vigente de exactamente 6 caracteres",
            "Marcar el código como usado (no reutilizable)",
            "Rechazar inexistente, usado, vencido, longitud distinta de 6",
            "NO insertar voto",
        ],
        "out_scope": [
            "El voto en sí (HU-006)",
            "TTL entre validar y depositar (no definido)",
            "Si hay que volver a validar para votar (no definido)",
        ],
        "pre": "HU-004: existe un OTP vigente no usado para ese aprendiz y esa elección.",
        "post": "OTP marcado usado. Cero votos nuevos. El paso de confirmar candidato puede abrirse (la precondición de HU-006 respecto a OTP sigue sujeta a P3).",
        "trigger": "Envía el código recibido.",
        "permisos_si": "Aprendiz dueño de ese OTP.",
        "permisos_no": "Validar el OTP de otro aprendiz.",
        "entidades": "ValidacionVoto",
        "campos": "codigo (exactamente 6) · estado usado/vigente/vencido",
        "rn": "RN-SIG-002, RN-SIG-003",
        "rnf": "RNF-NU-001",
        "deps": "HU-004-AP",
        "bloquea": "HU-006 (si el PO confirma OTP como precondición del voto)",
        "dueno": "Alex / Sofia OTP",
        "dor": "Parcial — TTL post-validación no definido",
        "dor_gap": "P3 ¿el voto exige OTP recién validado? P4 ¿cuánto tiempo hay para depositar? P16 reutilizar si cierra el navegador.",
        "invest": "Cumple. Validar != votar. No fusionar con 004 ni 006.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Assert SQL: después de validar bien, count(votos) igual que antes. Código de 5 y de 7 caracteres = rechazo. Reusar el mismo código = rechazo.",
        "notas_dev": "POST /api/validaciones/validarOtp. Marcar usado. No tocar votoxcandidato.",
        "preguntas": "P3 OTP en el voto · P4 TTL · P16 reutilización",
        "tareas": "BE validarOtp · marcar usado · tests CP-005-*",
        "ca": [
            ca("CA-01", "Feliz",
               "un código vigente de exactamente 6 caracteres, no usado, de ese aprendiz y esa elección",
               "lo valida",
               "se acepta y NO se inserta ningún voto"),
            ca("CA-02", "Excepción",
               "un código inexistente, ya usado o vencido",
               "intenta validar",
               "se rechaza y no hay voto"),
            ca("CA-03", "Validación",
               "un código con longitud distinta de 6",
               "intenta validar",
               "se rechaza"),
        ],
        "ca_cond": [
            ca("CA-P04", "Condicionado",
               "el OTP ya fue validado hace N minutos",
               "el aprendiz intenta votar",
               "N no está definido. No implementar un TTL inventado. Dejar explícito en RF que está pendiente."),
        ],
        "cp": [
            cp("CP-005-01", "CA-01", "Válido", "Acepta; count votos igual"),
            cp("CP-005-02", "CA-02", "Vencido", "Rechazo", "Excepción"),
            cp("CP-005-03", "CA-02", "Ya usado", "Rechazo", "Excepción"),
            cp("CP-005-04", "CA-02", "Inventado", "Rechazo", "Excepción"),
            cp("CP-005-05", "CA-03", "5 caracteres", "Rechazo", "Validación"),
            cp("CP-005-06", "CA-03", "7 caracteres", "Rechazo", "Validación"),
        ],
        "riesgo": "Alto si validar escribe voto. Medio por TTL abierto (no bloquea documentar; sí bloquea un reloj post-OTP en código).",
        "estado": "Especificada · DoR parcial",
    },
    {
        "id": "HU-SIG-006-AP",
        "sheet": "HU-006-AP",
        "titulo": "Registrar un voto único",
        "como": "Aprendiz",
        "quiero": "votar una sola vez en esa elección, por un candidato de ese tarjetón",
        "para": "cumplir un ciudadano, un voto, con evidencia en el sistema",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-010",
        "feature_nom": "Emisión de voto único",
        "rf": "RF-NU-006",
        "cu": "CU-06",
        "journey": "J-02 paso 6",
        "moscow": "MUST HAVE",
        "moscow_why": "Núcleo electoral. Si se puede votar dos veces, SIGEVA no es SIGEVA.",
        "sp": 8,
        "sp_why": "Unicidad real (reintento + carrera), circunscripción, pertenencia del candidato, ventana. El comprobante se deja en HU-007.",
        "rank": 12,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Invariante 1. El acta (HU-018) solo es defendible si esta historia no duplica.",
        "problema": "Doble clic, reintento, segunda pestaña o dos requests paralelos no pueden producir dos filas.",
        "exito": "Exactamente un registro de voto por par (aprendiz, elección). El segundo intento no inserta. Un candidato de otra elección se rechaza. Fuera de ventana se rechaza.",
        "in_scope": [
            "Insertar un voto por un candidato de ESA elección",
            "Impedir segundo insert del mismo aprendiz en la misma elección (reintento, doble clic, segunda pestaña)",
            "Dos peticiones simultáneas: persiste exactamente un voto (RN-001 cubre la carrera; no se acepta 'dos filas')",
            "Rechazar candidato de otra elección",
            "Rechazar fuera de ventana",
            "Marcar la validación como votada (VOTED_ u homólogo)",
        ],
        "out_scope": [
            "Pantalla de comprobante (HU-007)",
            "Voto en blanco / nulo (no hay HU)",
            "Cambiar el voto",
            "Ver totales",
            "Cómo técnico del lock (unique constraint vs transacción) es TAREA, no la historia — el resultado de negocio es uno",
        ],
        "pre": "HU-003 (candidato de ese tarjetón). HU-001. Elección en ventana y circunscripción. No existe voto previo. OTP validado SI el PO confirma P3; el backlog lo sugiere, el middleware actual no lo mira.",
        "post": "Una fila en votoxcandidato. El aprendiz no puede votar de nuevo en esa elección. Comprobante disponible (HU-007).",
        "trigger": "Confirma el candidato elegido.",
        "permisos_si": "Aprendiz, un voto, su elección.",
        "permisos_no": "Funcionario / Administrador no votan. Aprendiz no vota en otra circunscripción.",
        "entidades": "VotoXCandidato, Candidato, Aprendiz, Eleccion, ValidacionVoto",
        "campos": "idaprendiz (obligatorio) · idcandidatos (obligatorio, de esa elección) · no se envía un 'contador de votos' desde el cliente como fuente de verdad",
        "rn": "RN-SIG-001, RN-SIG-004, RN-SIG-005, RN-SIG-011",
        "rnf": "RNF-NU-002",
        "deps": "HU-003-AP; HU-005-AP (OTP validado: CONDICIONADO a P3)",
        "bloquea": "HU-007, HU-018 (acta con votos reales)",
        "dueno": "Alex",
        "dor": "Parcial — P3 OTP-en-voto no cerrado; el resultado de carrera SÍ está cerrado por RN-001",
        "dor_gap": "P3 ¿el POST de voto exige OTP validado en ese paso? P4 TTL. Implementar unique (aprendiz, elección) es tarea de DoD, no una pregunta de negocio: RN-001 ya dice un voto.",
        "invest": "Cumple si el comprobante queda fuera (007).",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Prueba de carrera: dos POST paralelos del mismo aprendiz. Resultado: 1 fila, nunca 2. Candidato de elección B con id de elección A = rechazo. Ya votó + reintento = 0 inserts extra.",
        "notas_dev": "POST /api/votoXCandidato/crear. Constraint único real en BD. Middleware de unicidad. El middleware actual no mira OTP: alinear SOLO si P3 se cierra que sí. Reloj de ventana único con HU-002 y HU-004.",
        "preguntas": "P3 OTP en el mismo paso del voto. P4 TTL. La carrera NO es pregunta de '¿pueden ser dos?': RN-001 lo prohíbe. Sí puede quedar pendiente el copy del segundo request (error vs 'ya votó').",
        "tareas": "BE crear voto + unique + middleware · marcar VOTED_ · test de carrera · no mezclar comprobante",
        "ca": [
            ca("CA-01", "Feliz",
               "aprendiz en circunscripción, elección en ventana, candidato de ese tarjetón, sin voto previo",
               "confirma el voto",
               "se inserta exactamente un registro de voto y el aprendiz queda imposibilitado de votar de nuevo en esa elección"),
            ca("CA-02", "Excepción",
               "el aprendiz ya tiene voto en esa elección",
               "reintenta (mismo u otro candidato, mismo u otro clic)",
               "no hay un segundo insert; se informa que ya votó"),
            ca("CA-03", "Excepción",
               "el identificador de candidato pertenece a otra elección",
               "confirma",
               "se rechaza y no hay voto"),
            ca("CA-04", "Borde",
               "ahora está fuera de la ventana",
               "confirma",
               "se rechaza (invariante 4)"),
            ca("CA-05", "Borde",
               "el aprendiz aún no tiene voto y llegan dos peticiones de voto a la vez",
               "ambas se procesan",
               "el sistema persiste exactamente un voto; la otra no duplica. El copy del segundo request (error vs ya votó) puede unificarse en implementación, pero nunca dos filas"),
        ],
        "ca_cond": [
            ca("CA-P03", "Condicionado",
               "el aprendiz está logueado pero no hay OTP validado reciente",
               "intenta votar",
               "el backlog sugiere exigir OTP; el código hoy no lo mira. NO implementar ni relajar en silencio: documentar P3 en la tabla RF y esperar al PO."),
        ],
        "cp": [
            cp("CP-006-01", "CA-01", "Primer voto", "1 fila; aprendiz marcado votó"),
            cp("CP-006-02", "CA-02", "Segundo intento otro candidato", "Sigue 1 fila", "Excepción"),
            cp("CP-006-03", "CA-03", "Candidato ajeno", "Rechazo 0 inserts", "Excepción"),
            cp("CP-006-04", "CA-04", "Fuera de ventana", "Rechazo", "Borde"),
            cp("CP-006-05", "CA-05", "Doble POST paralelo", "Exactamente 1 fila", "Borde"),
        ],
        "riesgo": "Crítico. Unique en BD es DoD. Sin él, la HU no está hecha aunque la UI 'parezca' bloquear.",
        "estado": "Especificada · DoR parcial (P3)",
    },
    {
        "id": "HU-SIG-007-AP",
        "sheet": "HU-007-AP",
        "titulo": "Ver confirmación del voto (sin resultados)",
        "como": "Aprendiz que ya votó o que intenta votar de nuevo",
        "quiero": "ver que el voto quedó (o que ya había votado)",
        "para": "tener certeza de emisión SIN totales, SIN ganador y SIN reabrir la urna",
        "actor": "Aprendiz",
        "producto": "Urna",
        "modulo": "M-05 Urna",
        "epica": "EP-SIG-003",
        "epica_nom": "Urna",
        "feature": "FT-SIG-011",
        "feature_nom": "Comprobante sin resultados",
        "rf": "RF-NU-007",
        "cu": "CU-07",
        "journey": "J-02 paso 7",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin comprobante el votante desconfía. Con resultados, se rompe el secreto de escrutinio.",
        "sp": 2,
        "sp_why": "Mensaje + bloqueo de tarjetón + prohibición de llamar reporte. Poco código, alto valor de integridad.",
        "rank": 13,
        "fase": "C — Urna",
        "mvp": "Sí",
        "valor": "Cierra el journey del votante. Invariante de secreto (RN-007).",
        "problema": "El aprendiz no sabe si 'le cogió' el clic. La tentación de mostrar un tablero es el error de producto a evitar.",
        "exito": "Mensaje de éxito o de 'ya votó'. Cero totales. Cero ganador. La urna de esa elección no se reabre para votar otra vez. La UI no llama al reporte.",
        "in_scope": [
            "Mensaje de voto registrado",
            "Mensaje de ya votó",
            "Bloquear nueva emisión en esa elección",
            "No mostrar totales ni ganador",
        ],
        "out_scope": [
            "Acta PDF",
            "Publicar resultados después del cierre (pregunta P22: hoy el aprendiz no ve resultados en este producto)",
            "Número de radicado oficial tipo Registraduría (no hay HU)",
        ],
        "pre": "HU-006 corrió, o el aprendiz ya tenía voto.",
        "post": "El aprendiz tiene certeza visual. El escrutinio sigue oculto. No hay segundo voto.",
        "trigger": "Termina HU-006 o reingresa a una elección en la que ya votó.",
        "permisos_si": "Aprendiz, su comprobante.",
        "permisos_no": "No descarga acta. No ve reporte.",
        "entidades": "VotoXCandidato (existencia, no el desglose)",
        "campos": "texto de confirmación. PROHIBIDO: votos por candidato, ganador, participantes, PDF.",
        "rn": "RN-SIG-007, RN-SIG-001",
        "rnf": "RNF-NU-003, RNF-NU-004",
        "deps": "HU-006-AP",
        "bloquea": "Ninguna de producto",
        "dueno": "Alex",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Diseño del comprobante (DoR 12). P22 resultados post-cierre: fuera de esta HU.",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "DevTools: la urna no llama GET /api/reporte/eleccion/:id. Tras éxito, volver atrás no reabre el voto.",
        "notas_dev": "FE comprobante; bloquear tarjetón; nunca reporte en urna.",
        "preguntas": "P22 ¿el aprendiz verá resultados después del cierre? Hoy: nunca en este producto.",
        "tareas": "FE comprobante + guard de urna · Test CP-007-*",
        "ca": [
            ca("CA-01", "Feliz",
               "acaba de registrarse un voto nuevo",
               "se muestra la confirmación",
               "hay mensaje de éxito, no hay totales ni ganador, y la urna de esa elección no se reabre para votar otra vez"),
            ca("CA-02", "Feliz",
               "el aprendiz ya había votado",
               "vuelve a esa elección",
               "ve mensaje de 'ya votó', igual sin resultados, y no puede emitir otro voto"),
            ca("CA-03", "Seguridad",
               "la pantalla de comprobante o de urna post-voto",
               "se inspeccionan red y UI",
               "no hay llamada al reporte ni al acta"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-007-01", "CA-01", "Tras voto nuevo", "Éxito sin totales"),
            cp("CP-007-02", "CA-02", "Reingreso ya votó", "Mensaje ya votó; urna bloqueada"),
            cp("CP-007-03", "CA-03", "Red de la urna", "Cero GET reporte", "Seguridad"),
        ],
        "riesgo": "Medio de producto (filtrar resultados). Bajo técnico.",
        "estado": "Especificada",
    },
]
