# -*- coding: utf-8 -*-
"""Historias de mesa (funcionario) y login de gestión. IDs originales."""
from _excel_senior_helpers import ca, cp

HU_FUNCIONARIO = [
    {
        "id": "HU-SIG-010-GE",
        "sheet": "HU-010-GE",
        "titulo": "Iniciar sesión de gestión (Funcionario o Administrador)",
        "como": "Funcionario o Administrador",
        "quiero": "entrar por UNA sola puerta de gestión",
        "para": "abrir el menú de mi perfil sin duplicar el login ni mezclarlo con la urna",
        "actor": "Funcionario / Administrador",
        "producto": "Gestión",
        "modulo": "M-01 Identidad",
        "epica": "EP-SIG-001",
        "epica_nom": "Accesos",
        "feature": "FT-SIG-002",
        "feature_nom": "Acceso a gestión",
        "rf": "RF-NU-010",
        "cu": "CU-10",
        "journey": "J-03 / J-04 paso 1",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin esta puerta no hay mesa ni red. Un segundo login de admin rompería RN-008.",
        "sp": 5,
        "sp_why": "Una puerta, dos menús, centro atado al funcionario, inactivo no entra, error genérico, bcrypt. JWT queda fuera.",
        "rank": 1,
        "fase": "A — Cimientos",
        "mvp": "Sí",
        "valor": "Gobierno de la mesa y de la red empiezan aquí. El funcionario no elige sede: la sesión la trae.",
        "problema": "Dos logins de gestión o un login compartido con la urna mezclan poderes.",
        "exito": "Usuario activo Funcionario entra y su centro viaja en la sesión. Usuario activo Administrador entra y ve menú de red. Inactivo no entra. Aprendiz no administra por aquí. Contraseña no se relee.",
        "in_scope": [
            "Un formulario de gestión: correo + contraseña",
            "Autenticación bcrypt",
            "Menú según perfil (Funcionario vs Administrador)",
            "Funcionario: idcentro_formacion de su usuario, no un combo de sedes",
            "Estado inactivo → no entra",
            "Campos obligatorios",
            "Error genérico de credenciales",
        ],
        "out_scope": [
            "Login de urna (HU-001)",
            "JWT como historia (deuda técnica)",
            "SSO SENA, 2FA extra, recuperar contraseña",
            "Segundo login 'solo admin'",
            "Cerrar sesión (hueco; no hay HU)",
        ],
        "pre": "Existe al menos un usuario activo con perfil Funcionario o Administrador. El funcionario tiene centro asignado.",
        "post": "Sesión de gestión con perfil. Funcionario acotado a su centro. Contraseña no viaja de vuelta.",
        "trigger": "Envía correo y contraseña en la puerta de gestión.",
        "permisos_si": "Perfil Funcionario o Administrador, estado Activo.",
        "permisos_no": "Aprendiz. Usuario Inactivo.",
        "entidades": "Usuario, Perfil, CentroFormacion",
        "campos": "correo (obligatorio) · contraseña (obligatorio, no se relee) · salida: id, perfil, centro si funcionario. NUNCA password.",
        "rn": "RN-SIG-008, RN-SIG-013, RN-SIG-016",
        "rnf": "RNF-NU-001, RNF-NU-004",
        "deps": "Usuarios y perfiles existentes (HU-021 para mesas nuevas)",
        "bloquea": "HU-011 a HU-018, HU-020 a HU-025",
        "dueno": "Sofia escribe · Alex acepta seguridad",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Política de sesión API (token) es deuda, no esta HU. P15.",
        "invest": "Cumple. No es 'crear JWT'.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Funcionario inactivo = no entra. Body sin password. Aprendiz por esta puerta = no menú de gestión. Funcionario no recibe lista de centros para elegir.",
        "notas_dev": "POST /api/usuarios/login. FE una pantalla. Menú por perfil. JWT = tarea de deuda, no CA de esta HU.",
        "preguntas": "P13 logout · P15 ¿token en todos los POST? · P14 recuperar clave (fuera)",
        "tareas": "BE login gestión · FE puerta única · menú por perfil · tests CP-010-*",
        "ca": [
            ca("CA-01", "Feliz",
               "usuario activo Funcionario o Administrador con correo y contraseña válidos",
               "entra por la puerta de gestión",
               "autentica con bcrypt, el menú corresponde al perfil y la contraseña no se devuelve"),
            ca("CA-02", "Feliz",
               "el usuario es Funcionario",
               "entra",
               "la sesión trae SU centro; no hay selector de otra sede"),
            ca("CA-03", "Excepción",
               "usuario en estado Inactivo",
               "intenta entrar",
               "no entra"),
            ca("CA-04", "Permiso",
               "credenciales de Aprendiz",
               "se envían a la puerta de gestión",
               "no se abre el menú de mesa ni el de red"),
            ca("CA-05", "Seguridad",
               "correo inexistente o contraseña incorrecta",
               "intenta entrar",
               "error genérico del mismo tipo; no se indica si el correo existe"),
            ca("CA-06", "Validación",
               "falta correo o falta contraseña",
               "envía",
               "no autentica"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-010-01", "CA-01+02", "Funcionario activo", "Entra; hay centro; sin password"),
            cp("CP-010-02", "CA-01", "Administrador activo", "Entra; menú de red"),
            cp("CP-010-03", "CA-03", "Inactivo", "No entra", "Excepción"),
            cp("CP-010-04", "CA-04", "Aprendiz en gestión", "No menú de mesa", "Permiso"),
            cp("CP-010-05", "CA-05", "Clave mala vs correo inventado", "Mismo tipo de error", "Seguridad"),
            cp("CP-010-06", "CA-06", "Campos vacíos", "No autentica", "Validación"),
        ],
        "riesgo": "Alto de producto si se duplica el login de admin o si el funcionario elige centro.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-011-FU",
        "sheet": "HU-011-FU",
        "titulo": "Ver el panel de mi centro",
        "como": "Funcionario autenticado",
        "quiero": "ver el estado de la mesa de MI sede",
        "para": "saber qué hay que hacer en mi centro, sin datos de otras sedes y sin el tablero de red",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda / M-03 Censo",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-003",
        "feature_nom": "Panel de la mesa",
        "rf": "RF-NU-011",
        "cu": "CU-11",
        "journey": "J-03",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M original. No bloquea el voto: se puede importar, convocar y votar sin un dashboard. Mejora operación.",
        "sp": 5,
        "sp_why": "Aislamiento de centro es claro. Los widgets concretos no están firmados: 5 puntos asumen el mínimo de navegación, no un BI.",
        "rank": 17,
        "fase": "E — Red y operación (después del piloto de urna)",
        "mvp": "No (piloto de un centro puede vivir sin panel rico)",
        "valor": "El jurado ve 'su' mesa. Reduce la tentación de entrar al tablero de red.",
        "problema": "Sin panel, el funcionario vive en URLs sueltas. El riesgo es mostrarle cifras de otra sede o de la red.",
        "exito": "Todo lo visible está filtrado por idcentro_formacion de la sesión. No entra a HU-020. Estado vacío si no hay elecciones, no un error. Aprendiz no entra.",
        "in_scope": [
            "Superficie de inicio de la mesa, acotada al centro de la sesión",
            "No mostrar datos de otros centros",
            "No mostrar el tablero de red (HU-020)",
            "Estado vacío comprensible si aún no hay elecciones/censo",
            "Navegación hacia las acciones de mesa ya cubiertas por otras HU (importar, elecciones, candidatos, acta)",
        ],
        "out_scope": [
            "KPIs numéricos no firmados (n votos, % participación, comparativo nacional)",
            "Impersonar otra mesa",
            "El tablero de red",
        ],
        "pre": "HU-010. Usuario Funcionario con centro.",
        "post": "El funcionario está orientado en SU centro. Cero fugas de otras sedes.",
        "trigger": "Abre gestión tras login de funcionario.",
        "permisos_si": "Funcionario, su centro.",
        "permisos_no": "Aprendiz. Administrador no 'se hace' funcionario de una sede en esta HU.",
        "entidades": "Eleccion, Aprendiz, CentroFormacion (solo lectura acotada)",
        "campos": "CERRADO: idcentro de sesión como único filtro. PROPUESTO (no MUST, pendiente PO): recuento de elecciones del centro, aviso si hay una en ventana, atajos a importar / listar / acta.",
        "rn": "RN-SIG-008, RN-SIG-009",
        "rnf": "RNF-NU-004",
        "deps": "HU-010-GE",
        "bloquea": "Ninguna del voto",
        "dueno": "Paula",
        "dor": "Parcial — aislamiento Ready; widgets no Ready",
        "dor_gap": "Lista de indicadores no cerrada. No inventar un dashboard. El CA de aislamiento SÍ se prueba.",
        "invest": "Parcial (V y T del aislamiento sí; Small/Testable de widgets no, hasta que el PO liste 2-4 indicadores).",
        "invest_ok": "Parcial INVEST",
        "notas_qa": "Dos centros: el funcionario A no ve elecciones ni padrones de B. Intento de URL de tablero de red = 403 u oculto. Aprendiz 403.",
        "notas_dev": "FE home de mesa. BE consultas con WHERE centro = sesión. Nunca confiar en un idcentro que mande el cliente si no coincide con la sesión.",
        "preguntas": "¿Qué widgets son obligatorios? No se inventan. Propuesta de análisis (no CA MUST): n elecciones del centro, si hay una en ventana, atajo a importar/listar/acta.",
        "tareas": "FE panel acotado · BE queries de sesión · Test de aislamiento",
        "ca": [
            ca("CA-01", "Feliz",
               "un funcionario autenticado",
               "abre el panel",
               "solo ve información de su idcentro_formacion"),
            ca("CA-02", "Permiso",
               "un funcionario autenticado",
               "intenta abrir el tablero de red (HU-020)",
               "no entra"),
            ca("CA-03", "Vacío",
               "su centro aún no tiene elecciones",
               "abre el panel",
               "ve un estado vacío entendible, no un error de servidor"),
            ca("CA-04", "Permiso",
               "un aprendiz",
               "pide el panel de mesa",
               "no se le sirve"),
        ],
        "ca_cond": [
            ca("CA-W", "Condicionado — widgets",
               "el PO aún no firmó indicadores",
               "alguien pide 'mostrar participación %'",
               "NO se implementa como MUST. Queda propuesta de análisis, no criterio de aceptación cerrado."),
        ],
        "cp": [
            cp("CP-011-01", "CA-01", "Solo su centro", "Cero filas de otra sede"),
            cp("CP-011-02", "CA-02", "URL de red", "403 u oculto", "Permiso"),
            cp("CP-011-03", "CA-03", "Centro sin elecciones", "Empty state", "Vacío"),
            cp("CP-011-04", "CA-04", "Aprendiz", "No sirve panel", "Permiso"),
        ],
        "riesgo": "Medio de fugas de datos si el API acepta idcentro del query string.",
        "estado": "Especificada · DoR parcial (widgets)",
    },
    {
        "id": "HU-SIG-012-FU",
        "sheet": "HU-012-FU",
        "titulo": "Importar el Excel del censo de MI centro",
        "como": "Funcionario",
        "quiero": "subir el Excel institucional de ficha SENA",
        "para": "habilitar quién vota en mi sede sin tipear persona a persona y sin apuntar a otra sede",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-03 Censo",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-004",
        "feature_nom": "Importación de censo (centro = sesión)",
        "rf": "RF-NU-012",
        "cu": "CU-12",
        "journey": "J-01 paso 3 / J-03",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin padrón no hay urna. Es el MUST de mesa de un centro. Distinta de HU-024.",
        "sp": 13,
        "sp_why": "Parseo de plantilla SENA + persistencia + bcrypt de clave temporal + informe de insertados/actualizados/omitidos. Candidata a partir en poker (parsear | persistir) si el equipo la ve enorme. NO fusionar con 024.",
        "rank": 3,
        "fase": "B — Mesa de un centro",
        "mvp": "Sí",
        "valor": "Convierte la ficha SENA en padrón. El centro lo pone la sesión: no se puede 'ayudar' a otra sede.",
        "problema": "Listas sueltas y Excel que cada quien interpreta. Un funcionario bienintencionado cargando otro centro rompe la circunscripción.",
        "exito": "C2 = ficha; filas desde la 5; centro = sesión; respuesta con insertados/actualizados/omitidos; sin archivo o C2 ilegible no importa.",
        "in_scope": [
            "Upload del Excel de ficha",
            "Leer grupo/ficha en C2",
            "Leer aprendices desde la fila 5",
            "Centro impuesto por la sesión (ignorado cualquier centro que venga en el archivo)",
            "Alta o actualización de aprendices del padrón",
            "Informe: insertados / actualizados / omitidos",
            "Rechazo sin archivo o con ficha ilegible",
        ],
        "out_scope": [
            "Elegir el centro destino (eso es HU-024, solo Administrador)",
            "Alta puntual por formulario (HU-023)",
            "Que el funcionario reciba un combo de sedes",
        ],
        "pre": "HU-010. Centro de sesión válido. Plantilla SENA conocida.",
        "post": "Padrón del centro actualizado. Claves temporales hasheadas (bcrypt). Informe de corrida. Cero aprendices colgados en otro centro por esta vía.",
        "trigger": "Sube el archivo desde la mesa.",
        "permisos_si": "Funcionario, su centro.",
        "permisos_no": "Aprendiz. Administrador usa HU-024, no esta vía, para elegir sede.",
        "entidades": "Aprendiz, Grupo, ProgramaFormacion, CentroFormacion",
        "campos": "archivo xlsx · C2 ficha · filas ≥5. Body: ⚠️ el código pide 'jornada'; el backlog de HU no la nombra. P19 abierta: no afirmar que es obligatoria en esta mesa hasta que el PO cierre.",
        "rn": "RN-SIG-009, RN-SIG-013, RN-SIG-017, RN-SIG-020",
        "rnf": "RNF-NU-001",
        "deps": "HU-010-GE",
        "bloquea": "HU-001 (urna), HU-016 (candidato del censo)",
        "dueno": "Paula",
        "dor": "Ready para especificar el camino feliz · P19 jornada en body pendiente",
        "dor_gap": "P19 ¿jornada en el body es obligatoria o sale de la ficha/Excel?",
        "invest": "Valiosa y testeable. Estimable alta (13). Independiente de 024 (NO fusionar).",
        "invest_ok": "Cumple INVEST (partir si poker pide)",
        "notas_qa": "Un Excel con 'otro centro' escrito en alguna celda: igual cae en el centro de sesión. Funcionario de centro A no logra persistir en B. C2 vacío = no importa. Respuesta tiene tres contadores.",
        "notas_dev": "POST /api/aprendices/importarExcel. Parser xlsx. bcrypt clave temporal. FE upload. Test con fixture de plantilla SENA. Distinto endpoint/regla que 024.",
        "preguntas": "P19 jornada en body.",
        "tareas": "BE parser + persistir + informe · FE upload · tests plantilla · no fusionar 024",
        "ca": [
            ca("CA-01", "Feliz",
               "funcionario autenticado y un Excel de ficha válido",
               "importa",
               "los aprendices quedan en el centro de la SESIÓN, no en un centro leído del archivo"),
            ca("CA-02", "Feliz",
               "el archivo sigue la plantilla",
               "se procesa",
               "la ficha se lee en C2 y las filas de aprendices desde la 5"),
            ca("CA-03", "Feliz",
               "la corrida termina",
               "se muestra el resultado",
               "hay conteo de insertados, actualizados y omitidos"),
            ca("CA-04", "Permiso",
               "esta vía vs la del administrador",
               "se compara la regla de centro",
               "aquí el centro lo impone la sesión; en HU-024 el administrador elige centro. El funcionario no usa 024 para otra sede"),
            ca("CA-05", "Excepción",
               "no hay archivo, o C2 está vacío/ilegible",
               "intenta importar",
               "no se importa el padrón"),
        ],
        "ca_cond": [
            ca("CA-P19", "Condicionado",
               "el código actual pide jornada en el body",
               "el funcionario importa",
               "el backlog de esta HU no declara jornada obligatoria. No se escribe como RF cerrado hasta P19."),
        ],
        "cp": [
            cp("CP-012-01", "CA-01+02+03", "Import feliz de su centro", "Padrón en su centro; tres contadores"),
            cp("CP-012-02", "CA-01", "Archivo que 'menciona' otra sede", "Igual persiste en sesión", "Permiso"),
            cp("CP-012-03", "CA-05", "C2 vacío", "No importa", "Excepción"),
            cp("CP-012-04", "CA-05", "Sin archivo", "No importa", "Excepción"),
            cp("CP-012-05", "CA-04", "Funcionario no elige sede ajena", "No hay combo de centros", "Permiso"),
        ],
        "riesgo": "Alto de integridad de padrón. SP 13: riesgo de sprint si no se parte.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-013-FU",
        "sheet": "HU-013-FU",
        "titulo": "Crear una elección de mi centro",
        "como": "Funcionario",
        "quiero": "crear una elección con jornada y ventana de fecha y hora",
        "para": "convocar la urna oficial de mi centro, no un 'voten cuando puedan'",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-005",
        "feature_nom": "Convocatoria de elección",
        "rf": "RF-NU-013",
        "cu": "CU-13",
        "journey": "J-01 paso 4",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin convocatoria no hay ventana. Invariante 4 nace aquí.",
        "sp": 5,
        "sp_why": "Formulario con jornada enum + inicio≤fin fecha-hora + centro de sesión.",
        "rank": 4,
        "fase": "B — Mesa de un centro",
        "mvp": "Sí",
        "valor": "Pone horario oficial a la urna de esa sede.",
        "problema": "Convocatorias verbales o grupos de WhatsApp sin cierre.",
        "exito": "Elección atada al centro del funcionario, jornada ∈ {Mañana, Tarde, Noche}, inicio ≤ fin (fecha y hora), nombre y ventana obligatorios.",
        "in_scope": [
            "Alta de elección: nombre, jornada, fecha_inicio, hora_inicio, fecha_fin, hora_fin",
            "Centro = sesión",
            "Validar jornada y orden de ventana",
        ],
        "out_scope": [
            "Crear elección de otro centro",
            "El administrador crea elecciones (no hay HU; P10)",
            "Editar después (HU-014)",
            "Prohibir inicio en el pasado (el código no lo impide; no se afirma como RN nueva)",
        ],
        "pre": "HU-010. Centro de sesión.",
        "post": "Existe una elección de ese centro lista para recibir candidatos (HU-016).",
        "trigger": "Envía el formulario de nueva elección.",
        "permisos_si": "Funcionario, su centro.",
        "permisos_no": "Aprendiz. Otro centro.",
        "entidades": "Eleccion, CentroFormacion",
        "campos": "nombre (obligatorio) · jornada (Mañana|Tarde|Noche) · fecha_inicio, hora_inicio, fecha_fin, hora_fin (obligatorios, inicio ≤ fin)",
        "rn": "RN-SIG-012, RN-SIG-009",
        "rnf": "RNF-NU-002",
        "deps": "HU-010-GE",
        "bloquea": "HU-016, HU-002",
        "dueno": "Paula",
        "dor": "Ready para especificar el alta",
        "dor_gap": "¿Se puede crear con inicio ya pasado? El código lo permite. No se inventa la prohibición (dejar nota en RF).",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Jornada 'Madrugada' = rechazo. Inicio 10:00 fin 09:00 mismo día = rechazo. La elección queda con el centro del login, no con un id enviado a mano.",
        "notas_dev": "POST /api/eleccion/crear. Forzar idcentro de sesión. Validar enum y timestamps.",
        "preguntas": "¿Alta con inicio en el pasado? No cerrado. No inventar.",
        "tareas": "BE crear · FE formulario · validar jornada y ventana · tests",
        "ca": [
            ca("CA-01", "Feliz",
               "datos completos, jornada válida, inicio ≤ fin",
               "el funcionario crea",
               "la elección queda atada a su centro y lista para candidatos"),
            ca("CA-02", "Validación",
               "jornada distinta de Mañana, Tarde o Noche",
               "envía",
               "no se crea"),
            ca("CA-03", "Validación",
               "inicio posterior a fin (fecha o hora)",
               "envía",
               "no se crea"),
            ca("CA-04", "Validación",
               "falta nombre o falta alguna parte de la ventana",
               "envía",
               "no se crea"),
            ca("CA-05", "Permiso",
               "el funcionario",
               "intenta crear una elección con otro idcentro",
               "el sistema ignora ese intento y no crea en sede ajena"),
        ],
        "ca_cond": [
            ca("CA-PASADO", "Condicionado",
               "fecha-hora de inicio ya pasó",
               "crea la elección",
               "el as-is no lo impide. No se escribe 'debe rechazar' hasta que el PO lo pida."),
        ],
        "cp": [
            cp("CP-013-01", "CA-01", "Alta válida", "Queda en su centro"),
            cp("CP-013-02", "CA-02", "Jornada inválida", "Rechazo", "Validación"),
            cp("CP-013-03", "CA-03", "Inicio > fin", "Rechazo", "Validación"),
            cp("CP-013-04", "CA-04", "Sin nombre", "Rechazo", "Validación"),
            cp("CP-013-05", "CA-05", "idcentro ajeno en body", "No crea en sede ajena", "Permiso"),
        ],
        "riesgo": "Medio: ventana mal validada abre urna eterna o invertida.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-014-FU",
        "sheet": "HU-014-FU",
        "titulo": "Actualizar una elección de mi centro",
        "como": "Funcionario",
        "quiero": "corregir nombre, jornada o ventana de una elección de mi centro",
        "para": "ajustar la convocatoria sin moverla de sede",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-005",
        "feature_nom": "Convocatoria de elección",
        "rf": "RF-NU-014",
        "cu": "CU-14",
        "journey": "J-03",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M original. El piloto puede vivir si la elección se crea bien a la primera. Editar en caliente es riesgo electoral.",
        "sp": 5,
        "sp_why": "Las validaciones copian a 013. El costo real es la regla de 'ya abrió / ya hay votos', que NO está lista.",
        "rank": 18,
        "fase": "F — Ajustes con reglas cerradas",
        "mvp": "No",
        "valor": "Corregir un typo de nombre o un horario mal digitado ANTES de que la urna sea un hecho.",
        "problema": "Cambiar la ventana con gente ya votando reescribe la elección. Nadie firmó qué hacer.",
        "exito": "Puede cambiar nombre/jornada/ventana de UNA elección de SU centro, con las mismas validaciones del alta, SIN cambiar el centro. El caso con urna abierta o con votos está BLOQUEADO hasta P1.",
        "in_scope": [
            "Editar nombre, jornada, fecha/hora de una elección del centro de sesión",
            "Validaciones idénticas a HU-013",
            "No cambiar el centro",
            "No editar elección de otra sede",
        ],
        "out_scope": [
            "Mover la elección de centro",
            "Regla de edición con votos o urna abierta (P1 / RN-P02) — NO se implementa una política inventada",
        ],
        "pre": "HU-013. Elección del propio centro.",
        "post": "Datos de convocatoria actualizados SI el caso está permitido. Centro intacto.",
        "trigger": "Envía cambios de una elección propia.",
        "permisos_si": "Funcionario, elección de su centro.",
        "permisos_no": "Otras sedes. Aprendiz.",
        "entidades": "Eleccion",
        "campos": "nombre · jornada · ventana. idcentro NO es editable.",
        "rn": "RN-SIG-012. RN-P02 NO es regla todavía.",
        "rnf": "RNF-NU-002",
        "deps": "HU-013-FU",
        "bloquea": "Ninguna del voto si la elección nació bien",
        "dueno": "Paula",
        "dor": "NO READY para desarrollo de 'edición en caliente'. Ready solo para documentar el camino sin votos y la pregunta P1.",
        "dor_gap": "P1: ¿se puede modificar nombre/jornada/ventana ya abierta o con votos?",
        "invest": "Parcial. Independiente del voto hasta que exista la RN. Small se rompe si se mezcla 'typo antes de abrir' con 'cambiar reglas a mitad'.",
        "invest_ok": "Parcial INVEST — No Ready desarrollo en caliente",
        "notas_qa": "Hasta que exista RN: probar edición SIN votos y rechazo de sede ajena. El caso CON votos se registra como pendiente, no como bug si el código hoy deja editar.",
        "notas_dev": "No programar un 'si hay votos entonces X' sin P1. Si se implementa algo, solo el camino sin votos y dejar explícito el bloqueo.",
        "preguntas": "P1 / RN-P02. Obligatorio en la tabla RF como pregunta, no como invención.",
        "tareas": "Documentar CA cerrados + bloqueo P1 · no inventar política de votos",
        "ca": [
            ca("CA-01", "Feliz",
               "elección de su centro SIN votos y (hasta que P1 cierre) tratada como editable",
               "cambia nombre, jornada o ventana con datos válidos",
               "se actualiza y el centro no cambia"),
            ca("CA-02", "Permiso",
               "una elección de otro centro",
               "intenta editarla",
               "se rechaza"),
            ca("CA-03", "Validación",
               "jornada inválida o inicio > fin",
               "envía",
               "no actualiza (mismas reglas que el alta)"),
        ],
        "ca_cond": [
            ca("CA-P01", "BLOQUEADO",
               "la elección ya está en ventana o ya tiene votos",
               "el funcionario envía un cambio",
               "NO HAY regla. Desarrollo no elige entre 'bloquear', 'permitir' o 'anular votos'. Se documenta P1 y se espera al PO."),
        ],
        "cp": [
            cp("CP-014-01", "CA-01", "Update propio sin votos", "Cambia; centro igual"),
            cp("CP-014-02", "CA-02", "Elección ajena", "Rechazo", "Permiso"),
            cp("CP-014-03", "CA-03", "Inicio > fin", "No actualiza", "Validación"),
            cp("CP-014-04", "CA-P01", "Con votos / urna abierta", "PENDIENTE PO — no assert de negocio", "Condicionado"),
        ],
        "riesgo": "Alto electoral si se implementa a ciegas. Esta HU no entra a sprint de construcción hasta P1.",
        "estado": "No Ready (regla de votos / urna abierta)",
    },
    {
        "id": "HU-SIG-015-FU",
        "sheet": "HU-015-FU",
        "titulo": "Listar las elecciones de mi centro (también las cerradas)",
        "como": "Funcionario",
        "quiero": "ver TODAS las elecciones de mi centro, abiertas o no",
        "para": "administrar convocatoria, candidatos o el acta, no solo lo que está en ventana",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-005",
        "feature_nom": "Convocatoria de elección",
        "rf": "RF-NU-015",
        "cu": "CU-15",
        "journey": "J-03 / J-01 paso 13 (acta)",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin listar las cerradas el funcionario no llega al acta. No es un CRUD vanidoso.",
        "sp": 3,
        "sp_why": "Listado acotado al centro. La regla de valor es 'incluye cerradas'.",
        "rank": 5,
        "fase": "B — Mesa de un centro",
        "mvp": "Sí",
        "valor": "Puente entre convocatoria, tarjetón y acta. Distinto de HU-002 (el aprendiz solo ve activas de su circunscripción).",
        "problema": "Un listado 'solo abiertas' deja al jurado ciego el día siguiente.",
        "exito": "Todas las de su centro; cero otras sedes; incluye cerradas y futuras.",
        "in_scope": [
            "Listado completo del centro de sesión",
            "Incluir cerradas, vigentes y no abiertas aún",
            "Excluir otras sedes",
        ],
        "out_scope": [
            "Filtro de urna del aprendiz (HU-002)",
            "Tablero nacional (HU-020)",
        ],
        "pre": "HU-010.",
        "post": "El funcionario tiene el inventario de contiendas de su mesa.",
        "trigger": "Abre 'elecciones' de la mesa.",
        "permisos_si": "Funcionario, su centro.",
        "permisos_no": "Otras sedes. Aprendiz no usa este listado.",
        "entidades": "Eleccion",
        "campos": "id, nombre, jornada, ventana, (opcional) estado derivado de ahora vs ventana. Sin totales de votos en este listado (eso es HU-018).",
        "rn": "RN-SIG-008, RN-SIG-009",
        "rnf": "RNF-NU-004",
        "deps": "HU-010-GE",
        "bloquea": "HU-016 (elegir en cuál inscribir), HU-018 (elegir cuál actar)",
        "dueno": "Paula",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Ninguna de negocio.",
        "invest": "Cumple. El valor es 'también las cerradas'.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Crear una cerrada y una abierta: ambas salen para el funcionario. El aprendiz, en HU-002, solo ve la abierta. Centro B no aparece.",
        "notas_dev": "GET .../traerTodas/:idcentro acotado a sesión (no al parámetro libre si no coincide).",
        "preguntas": "Ninguna de negocio.",
        "tareas": "BE listado de sesión · FE tabla · tests cerradas vs urna",
        "ca": [
            ca("CA-01", "Feliz",
               "el centro tiene elecciones abiertas y cerradas",
               "el funcionario lista",
               "aparecen todas, no solo las de la ventana actual"),
            ca("CA-02", "Permiso",
               "existen elecciones de otros centros",
               "lista",
               "no aparecen"),
            ca("CA-03", "Feliz",
               "se compara con la urna",
               "un aprendiz consulta HU-002 sobre el mismo universo",
               "el aprendiz solo ve activas de su circunscripción; el funcionario ve el inventario completo de su sede"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-015-01", "CA-01", "Incluye cerradas", "Salen abiertas y cerradas"),
            cp("CP-015-02", "CA-02", "Otra sede", "Cero filas ajenas", "Permiso"),
            cp("CP-015-03", "CA-03", "Contraste con urna", "Aprendiz no ve cerradas"),
        ],
        "riesgo": "Bajo técnico. Alto de confusión si se fusiona con HU-002.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-016-FU",
        "sheet": "HU-016-FU",
        "titulo": "Inscribir un candidato en el tarjetón",
        "como": "Funcionario",
        "quiero": "inscribir a un aprendiz del censo con propuesta, número de tarjetón y foto opcional",
        "para": "presentar un tarjetón identificable, sin números repetidos en esa elección",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-006",
        "feature_nom": "Armado del tarjetón",
        "rf": "RF-NU-016",
        "cu": "CU-16",
        "journey": "J-01 paso 5",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin candidatos no hay urna. Deben ser personas del padrón, no extraños.",
        "sp": 5,
        "sp_why": "Alta con unicidad de número por elección + Cloudinary opcional + aprendiz existente.",
        "rank": 6,
        "fase": "B — Mesa de un centro",
        "mvp": "Sí",
        "valor": "El tarjetón deja de ser una lista de WhatsApp. RN-011.",
        "problema": "Candidatos que no están en el censo, o dos con el número 1.",
        "exito": "Candidato = aprendiz del padrón; número único por elección; propuesta y número presentes; foto opcional; elección de su centro.",
        "in_scope": [
            "Alta de candidato sobre un aprendiz existente",
            "Número de tarjetón único por elección",
            "Propuesta y número obligatorios (el backlog los menciona; confirmar redacción en RF)",
            "Foto opcional (Cloudinary)",
            "Solo en elecciones del centro del funcionario",
        ],
        "out_scope": [
            "Editar o retirar (HU-017)",
            "Candidato que no es aprendiz",
            "Orden privilegiado en urna (eso se resuelve en HU-003)",
        ],
        "pre": "HU-013. Censo con el aprendiz (HU-012 o 023/024).",
        "post": "El tarjetón de esa elección tiene un candidato más. HU-003 puede mostrarlo.",
        "trigger": "Envía inscripción.",
        "permisos_si": "Funcionario, elección de su centro, aprendiz del padrón.",
        "permisos_no": "Aprendiz no se autoinscribe por esta HU. Otra sede.",
        "entidades": "Candidato, Aprendiz, Eleccion",
        "campos": "idaprendiz (existente) · ideleccion (propia) · propuesta (obligatoria según backlog) · numero_tarjeton (único por elección) · foto (opcional)",
        "rn": "RN-SIG-011",
        "rnf": "—",
        "deps": "HU-013-FU; censo",
        "bloquea": "HU-003, HU-006, HU-018",
        "dueno": "Paula",
        "dor": "Ready para especificar · confirmar en RF si propuesta es 100% obligatoria (el backlog sí la nombra)",
        "dor_gap": "Obligatoriedad de propuesta: mencionada; dejarla explícita en la tabla RF.",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Dos candidatos número 5 en la misma elección = el segundo rechaza. Aprendiz inexistente = rechazo. Sin foto = ok. Elección de otro centro = rechazo.",
        "notas_dev": "Alta candidato + unique (ideleccion, numero_tarjeton). Cloudinary opcional.",
        "preguntas": "Confirmar propuesta obligatoria en RF (el backlog la da por dicha).",
        "tareas": "BE alta + unique tarjetón · FE form + foto opcional · tests",
        "ca": [
            ca("CA-01", "Feliz",
               "un aprendiz del censo y una elección del centro del funcionario",
               "inscribe con propuesta y número libre en esa elección",
               "el candidato queda en el tarjetón; la foto puede omitirse"),
            ca("CA-02", "Excepción",
               "el número de tarjetón ya existe en ESA elección",
               "inscribe",
               "se rechaza"),
            ca("CA-03", "Excepción",
               "el id de aprendiz no existe en el censo",
               "inscribe",
               "se rechaza"),
            ca("CA-04", "Validación",
               "faltan propuesta o número (según RF)",
               "envía",
               "no se crea"),
            ca("CA-05", "Permiso",
               "elección de otro centro",
               "intenta inscribir",
               "se rechaza"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-016-01", "CA-01", "Alta con foto y sin foto", "Queda inscrito"),
            cp("CP-016-02", "CA-02", "Tarjetón duplicado", "Rechazo", "Excepción"),
            cp("CP-016-03", "CA-03", "Aprendiz inexistente", "Rechazo", "Excepción"),
            cp("CP-016-04", "CA-04", "Sin propuesta", "No crea", "Validación"),
            cp("CP-016-05", "CA-05", "Elección ajena", "Rechazo", "Permiso"),
        ],
        "riesgo": "Medio: unique mal hecho permite dos 'número 1'.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-017-FU",
        "sheet": "HU-017-FU",
        "titulo": "Actualizar o retirar un candidato",
        "como": "Funcionario",
        "quiero": "editar propuesta, foto o número, o sacar un candidato de la elección",
        "para": "corregir el tarjetón cuando todavía corresponde",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-04 Contienda",
        "epica": "EP-SIG-002",
        "epica_nom": "Censo y convocatoria",
        "feature": "FT-SIG-006",
        "feature_nom": "Armado del tarjetón",
        "rf": "RF-NU-017",
        "cu": "CU-17",
        "journey": "J-03",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M. El piloto puede vivir si el tarjetón se arma bien. Retirar con votos es decisión de negocio no tomada.",
        "sp": 8,
        "sp_why": "Junta dos acciones (editar vs retirar) y una regla abierta. Conviene partir cuando exista RN-P01. 8 es señal de 'no entra así al sprint de código'.",
        "rank": 19,
        "fase": "F — Ajustes con reglas cerradas",
        "mvp": "No",
        "valor": "Corregir un typo o una foto ANTES de que haya votos.",
        "problema": "Retirar a alguien que ya recibió votos sin decir qué pasa con esos votos y con el acta.",
        "exito": "SIN votos: se puede editar propuesta/foto/número (único) o retirar. CON votos: BLOQUEADO hasta P2.",
        "in_scope": [
            "Editar propuesta, foto o número (único por elección) cuando NO hay votos",
            "Retirar candidato cuando NO hay votos",
            "Solo elecciones del propio centro",
        ],
        "out_scope": [
            "Política con votos (bloqueo, nulo, recálculo, dejar ceros) — no se inventa",
            "Fusionar con HU-016",
        ],
        "pre": "HU-016. Candidato de elección propia.",
        "post": "Tarjetón corregido si no había votos. Si había votos: ninguna política nueva en código.",
        "trigger": "Edita o retira un candidato.",
        "permisos_si": "Funcionario, su elección.",
        "permisos_no": "Otra sede. Aprendiz.",
        "entidades": "Candidato, VotoXCandidato (solo para saber si ya hay votos — no para definir la política)",
        "campos": "propuesta · foto · numero_tarjeton (único). Retiro: baja de la elección.",
        "rn": "RN-SIG-011. RN-P01 NO es regla.",
        "rnf": "—",
        "deps": "HU-016-FU",
        "bloquea": "Ninguna del voto si el tarjetón nació bien",
        "dueno": "Paula",
        "dor": "NO READY. No cumple Small/Independent hasta partir y cerrar votos.",
        "dor_gap": "P2 / RN-P01: ¿editar o retirar con votos? ¿qué pasa con votos y acta?",
        "invest": "No cumple Small ni Independent. Partir 'editar ficha' vs 'retirar' cuando exista la RN.",
        "invest_ok": "NO cumple INVEST — No Ready",
        "notas_qa": "Probar edición y retiro SIN votos. Unique de número. Caso CON votos = pendiente, no se fabrica expected.",
        "notas_dev": "No programar borrado físico de votos ni 'voto nulo' sin PO. Si hay código as-is que deja editar con votos, es hallazgo, no requisito.",
        "preguntas": "P2 obligatorio en tabla RF.",
        "tareas": "Documentar camino sin votos · bloquear desarrollo del camino con votos · partir cuando haya RN",
        "ca": [
            ca("CA-01", "Feliz",
               "candidato de su elección SIN votos",
               "edita propuesta, foto o número (único)",
               "se actualiza"),
            ca("CA-02", "Feliz",
               "candidato de su elección SIN votos",
               "lo retira",
               "deja de aparecer en el tarjetón"),
            ca("CA-03", "Validación",
               "el nuevo número ya lo tiene otro candidato de esa elección",
               "edita",
               "se rechaza"),
        ],
        "ca_cond": [
            ca("CA-P02", "BLOQUEADO",
               "ya hay al menos un voto en la elección o hacia ese candidato",
               "edita o retira",
               "NO HAY regla (¿bloqueo, ceros en acta, voto nulo?). Desarrollo no elige. Se espera P2."),
        ],
        "cp": [
            cp("CP-017-01", "CA-01", "Editar sin votos", "Actualiza"),
            cp("CP-017-02", "CA-02", "Retirar sin votos", "Sale del tarjetón"),
            cp("CP-017-03", "CA-03", "Número duplicado", "Rechazo", "Validación"),
            cp("CP-017-04", "CA-P02", "Con votos", "PENDIENTE PO", "Condicionado"),
        ],
        "riesgo": "Crítico si se implementa el retiro con votos. No entra a sprint de construcción.",
        "estado": "No Ready",
    },
    {
        "id": "HU-SIG-018-FU",
        "sheet": "HU-018-FU",
        "titulo": "Generar reporte y acta PDF",
        "como": "Funcionario",
        "quiero": "ver el reporte y descargar el acta de una elección de mi centro",
        "para": "dejar constancia de votos por candidato (incluidos ceros), participantes distintos y ganador o empate",
        "actor": "Funcionario",
        "producto": "Mesa",
        "modulo": "M-06 Escrutinio",
        "epica": "EP-SIG-004",
        "epica_nom": "Acta",
        "feature": "FT-SIG-012",
        "feature_nom": "Acta y reporte",
        "rf": "RF-NU-018",
        "cu": "CU-18",
        "journey": "J-01 paso 13",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin acta reconstruible no hay elección defendible. Cierra el ciclo de un centro.",
        "sp": 8,
        "sp_why": "Agregación correcta (ceros, distinct, empate) + PDF. No es un 'export' tonto.",
        "rank": 14,
        "fase": "D — Acta",
        "mvp": "Sí",
        "valor": "Invariante 5. El número publicado sale de los votos guardados.",
        "problema": "Conteo oral, tablero y Excel paralelo que no coinciden con la urna.",
        "exito": "Todos los candidatos aparecen aunque tengan 0. Participantes = aprendices distintos. Un máximo único = ganador; dos o más con el máximo = empate declarado (no hay segunda vuelta en este producto). El aprendiz no ve ni descarga el acta.",
        "in_scope": [
            "Reporte por elección del centro",
            "Totales por candidato incluyendo ceros",
            "Participantes = COUNT DISTINCT de aprendices que votaron",
            "Ganador o declaración de empate",
            "PDF descargable por el funcionario de esa mesa",
            "Reconstrucción desde votos (no un total guardado a mano)",
        ],
        "out_scope": [
            "El aprendiz ve resultados (HU-007 lo prohíbe)",
            "Publicación pública",
            "Segunda vuelta o sorteo (P21: hoy se declara empate)",
            "Admin descarga actas de toda la red (P9, no hay HU)",
            "Biometría / recuento físico",
        ],
        "pre": "HU-016 (hay tarjetón, aunque sea con ceros). Votos si ya hubo urna. Elección del propio centro.",
        "post": "El jurado tiene un artefacto defendible. Los números coinciden con SELECT de votos.",
        "trigger": "Pide reporte / descarga PDF de una elección de su centro.",
        "permisos_si": "Funcionario, elección de su centro.",
        "permisos_no": "Aprendiz. ⚠️ Administrador: no hay HU de acta de red (P8/P9).",
        "entidades": "VotoXCandidato, Candidato, Eleccion, Aprendiz",
        "campos": "por candidato: nombre, número, votos (≥0) · participantes distintos · resultado: ganador | empate",
        "rn": "RN-SIG-006, RN-SIG-007",
        "rnf": "RNF-NU-004",
        "deps": "HU-016-FU; votos de HU-006 si ya votaron",
        "bloquea": "Ninguna",
        "dueno": "Paula · Alex invariante 5",
        "dor": "Ready para especificar el contenido del acta · P8 urna abierta pendiente",
        "dor_gap": "P8 ¿se genera con urna abierta (snapshot) o solo al cierre?",
        "invest": "Cumple. No fusionar con el comprobante del aprendiz.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Elección con 3 candidatos y 0 votos: tres filas en 0, participantes 0, sin ganador único (o empate de ceros: declarar según regla de máximo compartido). Dos candidatos con 10 y uno con 5: ganador claro. Dos con 10: empate, no inventar desempate. Aprendiz no descarga. Reconstruir: borrar el PDF, regenerar, mismos números.",
        "notas_dev": "GET /api/reporte/eleccion/:id acotado a centro de sesión. FE PDF (jsPDF u homólogo). Nunca un total desnormalizado que se pueda editar a mano.",
        "preguntas": "P8 urna abierta · P9/P8 admin · P21 empate (hoy: se declara; no hay HU de desempate)",
        "tareas": "BE agregación + ceros + distinct + empate · FE PDF · tests invariante 5 · 403 aprendiz",
        "ca": [
            ca("CA-01", "Feliz",
               "una elección con candidatos, algunos con 0 votos",
               "se genera el reporte",
               "TODOS los candidatos aparecen, también los de cero"),
            ca("CA-02", "Feliz",
               "un aprendiz votó (aunque el cliente hubiera reintentado)",
               "se cuentan participantes",
               "participantes = aprendices DISTINTOS, no filas duplicadas"),
            ca("CA-03", "Feliz",
               "un candidato tiene el máximo estricto",
               "se calcula el resultado",
               "se declara ganador"),
            ca("CA-04", "Feliz",
               "dos o más candidatos comparten el máximo de votos",
               "se calcula el resultado",
               "se declara empate; no se inventa un único ganador ni una segunda vuelta"),
            ca("CA-05", "Permiso",
               "un aprendiz autenticado",
               "pide el reporte o el PDF",
               "no se le sirve"),
            ca("CA-06", "Feliz",
               "el PDF ya se había generado y alguien vota después (si P8 lo permite) o se regenera",
               "se vuelve a pedir el acta",
               "los números salen otra vez de los votos actuales, no de un PDF viejo memorizado como fuente de verdad"),
        ],
        "ca_cond": [
            ca("CA-P08", "Condicionado",
               "la ventana de la elección todavía está abierta",
               "el funcionario pide el acta",
               "NO está escrito si se permite un snapshot o si se bloquea. No inventar. Documentar P8 en RF."),
        ],
        "cp": [
            cp("CP-018-01", "CA-01", "Ceros visibles", "Fila con 0 presente"),
            cp("CP-018-02", "CA-02", "Doble intento de un votante", "Participantes +1 no +2"),
            cp("CP-018-03", "CA-03", "Máximo único", "Ganador"),
            cp("CP-018-04", "CA-04", "Empate en el máximo", "Se declara empate"),
            cp("CP-018-05", "CA-05", "Aprendiz descarga", "No", "Permiso"),
            cp("CP-018-06", "CA-06", "Regenerar PDF", "Mismos números que la BD"),
        ],
        "riesgo": "Alto de credibilidad institucional. Un acta que no cuadra con la BD invalida el producto.",
        "estado": "Especificada · P8 abierto",
    },
]
