# -*- coding: utf-8 -*-
"""Datos de épicas e historias SIGEVA — nivel senior. No inventa reglas de negocio."""

# ---------------------------------------------------------------------------
# Épicas
# ---------------------------------------------------------------------------
EPICAS = [
    {
        "id": "EP-SIG-000",
        "nombre": "Documentos de requerimientos",
        "tipo": "ANÁLISIS (no es capacidad de producto)",
        "producto": "Análisis Sprint 1",
        "actor": "Equipo de análisis (Sofia, Alex, Paula, Maicol, Mebel)",
        "en_una_frase": "Dejar por escrito, con IDs y firmas, el producto as-is para que Henry y Jorge puedan aceptar alcance.",
        "problema": "El código ya existe y no hay artefactos de análisis firmables. Sin IGP, RF/RNF y un Word, el equipo implementa de memoria y el cliente no puede aceptar.",
        "valor": "Henry y Jorge aceptan o rechazan un alcance explícito. Las tablas RF alimentan los casos de uso. Nadie discute en desarrollo una regla que no está en el Word.",
        "exito": "Un Word institucional con cabecera IGP, 21 tablas RF alineadas 1:1 con las HU de producto, RNF-NU-001 a 005, IDs estables y espacio de firmas. Cero features nuevas de software en este sprint.",
        "alcance": "Cabecera IGP · tablas RF-NU-001…007, 010, 011…018, 020…025 · RNF-NU-001…005 · unificación de estilo · firmas. Las preguntas abiertas se escriben como pendientes, no se rellenan.",
        "fuera": "Código nuevo · JWT · multi-tenant · app móvil · cerrar RN-P01 a RN-P10 como si el PO ya hubiera contestado.",
        "features": "Ninguna de producto. Paquetes D01–D07 del Sprint 1 de requerimientos.",
        "historias": "No hay HU de urna. Trabajo: D01 cabecera, D02 urna, D03 login gestión, D04 mesa, D05 red, D06 RNF, D07 unificar y firmar.",
        "deps": "Ninguna de software. Depende de este paquete de épicas/historias/backlog.",
        "moscow": "MUST del Sprint 1 de requerimientos. No entra al product backlog de la urna.",
        "riesgo": "Tratar D01–D07 como si fueran historias de usuario confunde a quien lee el backlog. Van en hoja aparte.",
        "orden": "0",
        "como": "Equipo de análisis",
        "quiero": "un Word institucional con RF/RNF e IDs alineados a las HU",
        "para": "que el cliente acepte alcance sin que el equipo invente reglas en código",
    },
    {
        "id": "EP-SIG-001",
        "nombre": "Accesos",
        "tipo": "PRODUCTO",
        "producto": "Urna + Gestión",
        "actor": "Aprendiz, Funcionario, Administrador",
        "en_una_frase": "Cada rol entra por la puerta correcta y ve solo el menú de su perfil.",
        "problema": "Si urna y gestión se mezclan, un aprendiz administra o un funcionario vota. Se rompe la separación de poderes desde el primer clic.",
        "valor": "La circunscripción del votante y el gobierno de la mesa empiezan en el login. Sin esto no hay urna ni mesa.",
        "exito": "El aprendiz entra a la urna con correo del censo y no ve gestión. El funcionario entra a gestión, trae su centro y no elige otra sede. El administrador entra por la misma puerta de gestión y ve menú de red. Un inactivo no entra. Las contraseñas no viajan de vuelta.",
        "alcance": "Login de urna (HU-001) · login único de gestión (HU-010) · menú por perfil · centro atado a la sesión del funcionario · rechazo de inactivo · error genérico de credenciales · bcrypt.",
        "fuera": "JWT / SSO / 2FA extra · recuperar contraseña · cerrar sesión (huecos de journey; no hay HU) · login duplicado de administrador · que el administrador vote.",
        "features": "FT-SIG-001 Acceso a la urna · FT-SIG-002 Acceso a gestión",
        "historias": "HU-SIG-001-AP · HU-SIG-010-GE",
        "deps": "Censo con al menos un aprendiz (para 001). Al menos un usuario activo con perfil (para 010).",
        "moscow": "MUST HAVE",
        "riesgo": "Hoy el login de API no emite token. Eso es deuda técnica, no esta épica. No convertir JWT en historia de usuario.",
        "orden": "1",
        "como": "cada rol",
        "quiero": "entrar por la puerta que me corresponde y ver solo mi menú",
        "para": "que la urna no administre y la gestión no vote",
    },
    {
        "id": "EP-SIG-002",
        "nombre": "Censo y convocatoria",
        "tipo": "PRODUCTO",
        "producto": "Mesa de un centro",
        "actor": "Funcionario (jurado digital de UN centro)",
        "en_una_frase": "Dejar la mesa de un centro lista: padrón, elección con ventana y tarjetón.",
        "problema": "Sin censo cerrado y sin horario oficial no hay urna seria. El Excel suelto no es padrón. Un WhatsApp no es convocatoria.",
        "valor": "Habilita quién puede votar, cuándo y por quién, sin mezclar sedes. Es el prerrequisito de la urna.",
        "exito": "El funcionario importa el Excel de ficha SENA y el centro lo impone la sesión. Crea una elección con jornada Mañana/Tarde/Noche y ventana fecha-hora. Inscribe candidatos del censo con número único. Lista también las elecciones cerradas (para el acta). No opera otra sede.",
        "alcance": "Panel del centro (HU-011) · import Excel centro=sesión (HU-012) · crear/actualizar/listar elección (HU-013/014/015) · inscribir y editar/retirar candidato (HU-016/017).",
        "fuera": "Importación eligiendo centro (eso es EP-SIG-005 / HU-024) · acta (EP-SIG-004) · voto · que el funcionario cargue otra sede · CRUD de regionales o programas como valor de urna.",
        "features": "FT-SIG-003 Panel · FT-SIG-004 Import centro · FT-SIG-005 Convocatoria · FT-SIG-006 Tarjetón (armado)",
        "historias": "HU-SIG-011-FU a HU-SIG-017-FU",
        "deps": "EP-SIG-001 (gestión). Catálogo de centros. HU-021 si la mesa aún no tiene funcionario.",
        "moscow": "MUST HAVE — no adelantar urna si esta épica no está lista.",
        "riesgo": "HU-014 y HU-017 no están Ready mientras el PO no cierre qué pasa con votos / urna abierta. El panel (HU-011) tiene aislamiento cerrado y widgets pendientes.",
        "orden": "2",
        "como": "Funcionario",
        "quiero": "armar padrón, convocatoria y tarjetón de MI centro",
        "para": "abrir una urna oficial sin mezclar sedes",
    },
    {
        "id": "EP-SIG-003",
        "nombre": "Urna",
        "tipo": "PRODUCTO",
        "producto": "Urna del aprendiz",
        "actor": "Aprendiz (votante)",
        "en_una_frase": "El aprendiz elige representante una sola vez, en su circunscripción, sin ver totales ni ganador.",
        "problema": "Una encuesta, un grupo de WhatsApp o un formulario con contador no son urna. No impiden el doble voto con evidencia ni respetan centro, jornada y ventana.",
        "valor": "Derecho al voto remoto, único y acotado. Es el núcleo de SIGEVA. Si falla, el resto del sistema no importa.",
        "exito": "El aprendiz ve solo elecciones de su centro y jornada dentro de la ventana. Ve un tarjetón identificable, sin ranking ni resultados. Demuestra el buzón con OTP de 6 caracteres al correo del censo. Validar el código NO registra el voto. Confirma un candidato de ese tarjetón. El sistema persiste un solo voto. Recibe comprobante sin totales.",
        "alcance": "Votaciones de circunscripción (HU-002) · tarjetón (HU-003) · solicitar OTP (HU-004) · validar OTP (HU-005) · voto único (HU-006) · comprobante (HU-007).",
        "fuera": "Acta y totales · gestión · otras sedes · segundo voto · tratar el OTP como si fuera el voto · publicar ganador al aprendiz · voto en blanco/nulo (no hay HU) · biometría.",
        "features": "FT-SIG-007 Urna filtrada · FT-SIG-008 Consulta de tarjetón · FT-SIG-009 Verificación de buzón · FT-SIG-010 Emisión de voto · FT-SIG-011 Comprobante",
        "historias": "HU-SIG-002-AP a HU-SIG-007-AP",
        "deps": "EP-SIG-001 (login urna) · EP-SIG-002 (elección y candidatos de ese centro) · SMTP.",
        "moscow": "MUST HAVE",
        "riesgo": "Regla de oro: validar OTP ≠ votar. Reenvíos, TTL post-validación y si el voto exige OTP en el mismo paso siguen abiertos (no se inventan). RN-001 ya prohíbe un segundo voto, también en carrera.",
        "orden": "3",
        "como": "Aprendiz",
        "quiero": "votar una vez en mi urna, con prueba de buzón, sin ver quién va ganando",
        "para": "ejercer el derecho con evidencia de unicidad y secreto de escrutinio",
    },
    {
        "id": "EP-SIG-004",
        "nombre": "Acta",
        "tipo": "PRODUCTO",
        "producto": "Mesa de un centro",
        "actor": "Funcionario",
        "en_una_frase": "Constancia reconstruible de votos, participantes y ganador o empate, el mismo día.",
        "problema": "El tablero oral y el conteo a mano no se defienden. Un número publicado que no sale de los votos guardados no es acta.",
        "valor": "El resultado se puede mostrar y defender el mismo día. Cierra el ciclo electoral de un centro.",
        "exito": "El reporte incluye a todos los candidatos aunque tengan cero votos. Participantes = aprendices distintos, no filas duplicadas. Si hay un máximo único, hay ganador; si dos o más comparten el máximo, se declara empate (no hay segunda vuelta en este producto). El aprendiz no ve el acta. El PDF se reconstruye desde los votos.",
        "alcance": "Reporte + PDF (HU-018). Ceros incluidos. Empate declarado.",
        "fuera": "El aprendiz ve el acta · publicación pública · recuento biométrico · segunda vuelta / sorteo · historia de administrador descargando actas de toda la red (no existe; pregunta abierta).",
        "features": "FT-SIG-012 Acta y reporte",
        "historias": "HU-SIG-018-FU",
        "deps": "EP-SIG-003 (votos). Se puede generar con ceros antes de que haya votos. ¿Con urna abierta? Pendiente de PO (RN-P03).",
        "moscow": "MUST HAVE",
        "riesgo": "Si el PDF no sale de los votos, se rompe la invariante 5. No adelantar esta épica como 'dashboard' antes de que el voto exista.",
        "orden": "4",
        "como": "Funcionario",
        "quiero": "generar reporte y acta PDF de la elección de mi centro",
        "para": "dejar constancia defendible de votos, participantes y resultado",
    },
    {
        "id": "EP-SIG-005",
        "nombre": "Red institucional",
        "tipo": "PRODUCTO",
        "producto": "Red SENA (no una mesa)",
        "actor": "Administrador",
        "en_una_frase": "Operar todas las sedes sin que un funcionario salga de la suya.",
        "problema": "La red SENA no es un colegio de una sede. Sin rol de red no hay quién cree mesas ni quién cargue padrones eligiendo centro.",
        "valor": "Escala nacional del primer cliente. Cada centro tiene mesa operativa. Los padrones no se mezclan.",
        "exito": "El administrador crea funcionarios con centro obligatorio. Inactiva o reasigna sede. Importa el mismo Excel eligiendo destino. Da alta puntual. Consulta el censo sin ver contraseñas. El funcionario NO usa la importación que elige centro. El administrador NO vota y NO tiene un segundo login.",
        "alcance": "Tablero de red (HU-020) · crear/listar/actualizar funcionarios (HU-021/022) · alta puntual (HU-023) · import eligiendo centro (HU-024) · consulta de censo (HU-025).",
        "fuera": "Login duplicado de admin · voto del admin · multi-tenant real (tabla organización) · que el admin 'se haga funcionario' de una sede como HU · crear elecciones como administrador (no hay HU; pregunta abierta).",
        "features": "FT-SIG-013 a FT-SIG-017",
        "historias": "HU-SIG-020-AD a HU-SIG-025-AD",
        "deps": "EP-SIG-001. HU-021 es prerrequisito de una mesa nueva.",
        "moscow": "MUST para operación SENA. Tablero (020), alta puntual (023) y consulta (025) son SHOULD. Import eligiendo centro (024) y funcionarios (021/022) son MUST de red.",
        "riesgo": "Adelantar tablero de red sin una urna que ya vote es el error clásico de dashboard antes que voto. El piloto de un centro puede vivir sin 024 (usa 012).",
        "orden": "5",
        "como": "Administrador",
        "quiero": "habilitar mesas y padrones en cualquier centro sin mezclar sedes",
        "para": "operar la red SENA y no un colegio aislado",
    },
    {
        "id": "EP-SIG-006",
        "nombre": "Calidad electoral",
        "tipo": "PRODUCTO / RNF transversal (no es pantalla)",
        "producto": "Atraviesa urna, mesa y red",
        "actor": "Los tres roles",
        "en_una_frase": "Que una elección institucional remota se pueda defender: secretos, ventana, menús y fallo de correo sin voto fantasma.",
        "problema": "OTP en el JSON de producción, urna eterna, menús mezclados o un voto creado cuando SMTP falló convierten a SIGEVA en un formulario inseguro.",
        "valor": "Las cinco invariantes. Sin ellas SIGEVA deja de ser SIGEVA.",
        "exito": "Contraseñas con bcrypt y no se releen. OTP de 6 caracteres no viaja en la respuesta de producción. Fuera de fecha y hora no hay urna. Cada rol ve solo su menú. Si el correo falla, no queda un voto.",
        "alcance": "RNF-NU-001 (secretos) · RNF-NU-002 (ventana) · RNF-NU-004 (menús) · RNF-NU-005 (SMTP sin voto). RNF-NU-003 (camino corto del votante) es SHOULD de UX.",
        "fuera": "Helios / voto criptográfico · SLA numéricos no definidos (no se inventan 99% ni 200 ms) · JWT como historia de usuario · biometría.",
        "features": "No hay features de pantalla. Se citan como RNF en los CU que toquen.",
        "historias": "No hay HU de UI. Ítems de backlog: RNF-NU-001 a 005.",
        "deps": "Todas las épicas de urna, acceso y acta.",
        "moscow": "MUST HAVE (excepto RNF-003, SHOULD)",
        "riesgo": "Las rutas HTTP hoy no tienen middleware de rol. La matriz de permisos es papel hasta que exista gate de API (tarea, no HU).",
        "orden": "6",
        "como": "el producto",
        "quiero": "cumplir las cinco invariantes en cada flujo de urna y gestión",
        "para": "que el resultado de una elección remota se pueda defender",
    },
]
