# -*- coding: utf-8 -*-
"""Historias de administrador (red). IDs originales."""


from _excel_senior_helpers import ca, cp


HU_ADMIN = [
    {
        "id": "HU-SIG-020-AD",
        "sheet": "HU-020-AD",
        "titulo": "Ver el tablero institucional de la red",
        "como": "Administrador",
        "quiero": "ver totales de TODA la red, no de un solo centro",
        "para": "tener visibilidad de la operación SENA completa, sin que un funcionario vea esa torre",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-01 / red",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-013",
        "feature_nom": "Tablero de la red",
        "rf": "RF-NU-020",
        "cu": "CU-20",
        "journey": "J-04",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M original. Un piloto de un centro no lo necesita. La red SENA sí, después de que una mesa ya vote.",
        "sp": 5,
        "sp_why": "Aislamiento de rol es claro. Las métricas concretas no están firmadas.",
        "rank": 21,
        "fase": "E — Red (después de urna piloto)",
        "mvp": "No",
        "valor": "Coordinación nacional. No sustituye al acta de una mesa.",
        "problema": "Sin torre, cada sede es un silo. El riesgo inverso: un dashboard vacío de sentido o que filtre al funcionario.",
        "exito": "El administrador entra a un tablero de red. El funcionario no. El aprendiz no. Cero cifras inventadas como MUST.",
        "in_scope": [
            "Una vista de red exclusiva del Administrador",
            "El funcionario no entra (RN-008)",
            "El aprendiz no entra",
        ],
        "out_scope": [
            "Lista MUST de KPIs (centros, funcionarios activos, aprendices, elecciones abiertas) — PROPUESTA, no firmada",
            "Impersonar una mesa",
            "Acta consolidada nacional (no hay HU)",
        ],
        "pre": "HU-010 como Administrador.",
        "post": "Visibilidad de red. Cero acceso de funcionario a esa vista.",
        "trigger": "Abre el tablero institucional.",
        "permisos_si": "Administrador.",
        "permisos_no": "Funcionario, Aprendiz.",
        "entidades": "CentroFormacion, Usuario, Aprendiz, Eleccion (agregados, pendientes de lista)",
        "campos": "CERRADO: visibilidad de red vs no. PROPUESTO (no MUST): n centros, n funcionarios activos, n aprendices, n elecciones en ventana. El PO debe firmar la lista.",
        "rn": "RN-SIG-008",
        "rnf": "RNF-NU-004",
        "deps": "HU-010-GE",
        "bloquea": "Ninguna de urna",
        "dueno": "Maicol · Alex acepta",
        "dor": "Parcial — rol Ready; widgets no Ready",
        "dor_gap": "Lista de métricas no cerrada. No inventar dashboard.",
        "invest": "Parcial (igual que HU-011): el permiso sí; el contenido no.",
        "invest_ok": "Parcial INVEST",
        "notas_qa": "Funcionario 403/oculto. Aprendiz 403. Admin entra. No assert de cifras concretas hasta que el PO las firme.",
        "notas_dev": "FE tablero admin. Gate de rol. No reutilizar el panel HU-011.",
        "preguntas": "¿Qué cifras son obligatorias? Propuesta de análisis, no CA.",
        "tareas": "FE tablero · 403 funcionario · no inventar widgets MUST",
        "ca": [
            ca("CA-01", "Feliz",
               "un administrador autenticado",
               "abre el tablero",
               "ve una vista de TODA la red, no el panel de un solo centro"),
            ca("CA-02", "Permiso",
               "un funcionario autenticado",
               "intenta abrir este tablero",
               "no entra"),
            ca("CA-03", "Permiso",
               "un aprendiz",
               "pide esta vista",
               "no se le sirve"),
        ],
        "ca_cond": [
            ca("CA-W", "Condicionado",
               "nadie firmó la lista de indicadores",
               "se pide 'mostrar participación nacional'",
               "no es MUST. Propuesta: centros, funcionarios activos, aprendices, elecciones en ventana — a confirmar."),
        ],
        "cp": [
            cp("CP-020-01", "CA-01", "Admin entra", "Vista de red"),
            cp("CP-020-02", "CA-02", "Funcionario", "403/oculto", "Permiso"),
            cp("CP-020-03", "CA-03", "Aprendiz", "No sirve", "Permiso"),
        ],
        "riesgo": "Bajo de urna. Medio de producto si se adelanta al voto piloto.",
        "estado": "Especificada · DoR parcial",
    },
    {
        "id": "HU-SIG-021-AD",
        "sheet": "HU-021-AD",
        "titulo": "Crear un funcionario y asignarle centro",
        "como": "Administrador",
        "quiero": "crear un funcionario con centro obligatorio",
        "para": "dejar una mesa operativa en esa sede",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-01 Identidad",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-014",
        "feature_nom": "Mesa operativa (funcionarios)",
        "rf": "RF-NU-021",
        "cu": "CU-21",
        "journey": "J-01 paso 1 / J-04",
        "moscow": "MUST HAVE",
        "moscow_why": "Sin funcionario no hay mesa. Es el prerrequisito de HU-010/012 en una sede nueva.",
        "sp": 5,
        "sp_why": "Alta con correo único, perfil fijo, centro obligatorio, bcrypt, no releer clave.",
        "rank": 2,
        "fase": "A — Cimientos / habilitar mesa",
        "mvp": "Sí",
        "valor": "Enciende una mesa. RN-017 y RN-019.",
        "problema": "Sin este rol, cada centro es un silo sin jurado digital.",
        "exito": "Usuario con perfil Funcionario, estado Activo, centro obligatorio, correo único, password bcrypt no revisible.",
        "in_scope": [
            "Alta de usuario funcionario",
            "Correo único",
            "Perfil Funcionario (no se crea un admin por esta HU)",
            "Estado Activo",
            "Centro obligatorio",
            "Password almacenada con bcrypt y no se relee",
            "Campos incompletos → no crea",
        ],
        "out_scope": [
            "Crear administrador (no hay HU)",
            "El funcionario se auto-registra",
            "Elegir perfil libre en el form",
        ],
        "pre": "HU-010 como Administrador. Existe el centro en catálogo.",
        "post": "Ese funcionario puede entrar por HU-010 y operar HU-012+ en SU centro.",
        "trigger": "Envía el alta.",
        "permisos_si": "Administrador.",
        "permisos_no": "Funcionario no crea pares. Aprendiz no.",
        "entidades": "Usuario, Perfil, CentroFormacion",
        "campos": "correo (único, obligatorio) · contraseña (obligatorio, bcrypt, no relectura) · idcentro_formacion (obligatorio) · perfil = Funcionario · estado = Activo",
        "rn": "RN-SIG-017, RN-SIG-019, RN-SIG-013",
        "rnf": "RNF-NU-001",
        "deps": "HU-010-GE",
        "bloquea": "HU-010 del nuevo jurado, HU-012 de esa sede",
        "dueno": "Maicol · Alex acepta",
        "dor": "Ready para especificar / documentar",
        "dor_gap": "Ninguna de negocio.",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Correo duplicado = no crea. Sin centro = no crea. GET posterior no trae password. Perfil resultante = Funcionario.",
        "notas_dev": "POST /api/usuarios/funcionarios. bcrypt. serialize password null. Autorizar rol admin (hoy las rutas no tienen middleware: deuda, DoD de permiso).",
        "preguntas": "Ninguna de negocio para el alta.",
        "tareas": "BE alta · bcrypt · unique correo · FE form · 403 no-admin · tests",
        "ca": [
            ca("CA-01", "Feliz",
               "correo libre, centro existente, clave presente",
               "el administrador crea",
               "queda un usuario Funcionario Activo en ese centro; la clave se guarda con bcrypt y no se relee"),
            ca("CA-02", "Excepción",
               "el correo ya existe",
               "crea",
               "se rechaza"),
            ca("CA-03", "Validación",
               "falta el centro o faltan campos obligatorios",
               "envía",
               "no crea"),
            ca("CA-04", "Permiso",
               "un funcionario autenticado",
               "intenta esta alta",
               "se rechaza"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-021-01", "CA-01", "Alta feliz", "Funcionario activo; password ausente en GET"),
            cp("CP-021-02", "CA-02", "Correo duplicado", "Rechazo", "Excepción"),
            cp("CP-021-03", "CA-03", "Sin centro", "No crea", "Validación"),
            cp("CP-021-04", "CA-04", "Funcionario crea funcionario", "403", "Permiso"),
        ],
        "riesgo": "Medio: alta sin gate de rol (deuda API).",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-022-AD",
        "sheet": "HU-022-AD",
        "titulo": "Listar y actualizar funcionarios (inactivar / reasignar centro)",
        "como": "Administrador",
        "quiero": "ver funcionarios, inactivarlos o cambiarles el centro",
        "para": "operar mesas sin mezclar el censo de aprendices en ese listado",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-01 Identidad",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-014",
        "feature_nom": "Mesa operativa (funcionarios)",
        "rf": "RF-NU-022",
        "cu": "CU-22",
        "journey": "J-04",
        "moscow": "MUST HAVE",
        "moscow_why": "Una mesa con jurado que ya no está o que cambió de sede no puede quedar viva. Must de red (no del piloto de un centro si el jurado no se mueve).",
        "sp": 5,
        "sp_why": "Tres acciones en una HU ('operar mesas'). Partir si el poker pide 13. El valor es uno: gobernar al jurado.",
        "rank": 16,
        "fase": "E — Red",
        "mvp": "No estrictamente para el primer comicio de UN centro con jurado ya creado a mano.",
        "valor": "Ciclo de vida del jurado. RN-016: inactivo no entra.",
        "problema": "Listar aprendices junto a funcionarios. Borrar físico sin regla. Dejar un inactivo entrando.",
        "exito": "Lista solo funcionarios. Inactivar → HU-010 lo rechaza. Reasignar centro. No hay borrado físico hasta que el PO lo pida (P9).",
        "in_scope": [
            "Listar usuarios de perfil Funcionario (no el censo de aprendices)",
            "Pasar a Inactivo",
            "Cambiar idcentro_formacion",
        ],
        "out_scope": [
            "Borrado físico (P9: el backlog habla de inactivar; no se inventa DELETE)",
            "Editar aprendices en esta pantalla",
            "El funcionario se auto-inactiva (no hay HU)",
        ],
        "pre": "HU-021. HU-010 admin.",
        "post": "Mesas con jurado correcto. Un inactivo no entra a gestión.",
        "trigger": "Consulta la lista o envía un cambio de estado/centro.",
        "permisos_si": "Administrador.",
        "permisos_no": "Funcionario no lista la red de jurados. Aprendiz no.",
        "entidades": "Usuario, Perfil, CentroFormacion",
        "campos": "estado (Activo|Inactivo) · idcentro_formacion. Censo de aprendices NO aparece.",
        "rn": "RN-SIG-016, RN-SIG-008",
        "rnf": "RNF-NU-004",
        "deps": "HU-021-AD",
        "bloquea": "Ninguna de urna",
        "dueno": "Maicol",
        "dor": "Ready para especificar listar/inactivar/reasignar · P9 borrado físico abierto (se documenta como NO)",
        "dor_gap": "P9 ¿eliminar o solo inactivar? Hasta respuesta: solo inactivar.",
        "invest": "Parcial Small (tres acciones). Aceptable como 'operar mesas'; partir si poker ≥13.",
        "invest_ok": "Parcial INVEST (Small)",
        "notas_qa": "La lista no trae aprendices. Inactivar y luego login HU-010 = no entra. Reasignar centro A→B: deja de operar A. No hay botón borrar salvo que el PO lo pida.",
        "notas_dev": "GET/PUT funcionarios. Filtro perfil. No DELETE físico. Middleware admin.",
        "preguntas": "P9 solo inactivar vs borrar.",
        "tareas": "BE listar/inactivar/reasignar · FE · tests de no-mezcla y de login inactivo",
        "ca": [
            ca("CA-01", "Feliz",
               "existen funcionarios y aprendices",
               "el administrador lista",
               "ve funcionarios, no el censo de aprendices"),
            ca("CA-02", "Feliz",
               "un funcionario Activo",
               "pasa a Inactivo",
               "ese usuario ya no entra por HU-010"),
            ca("CA-03", "Feliz",
               "un funcionario de centro A",
               "se le asigna centro B",
               "su sesión futura opera B, no A"),
            ca("CA-04", "Permiso",
               "un funcionario",
               "pide esta lista de red",
               "no se le sirve"),
        ],
        "ca_cond": [
            ca("CA-P09", "Condicionado",
               "alguien pide 'eliminar'",
               "intenta un DELETE físico",
               "no hay HU de borrado. Se inactiva. P9 abierta."),
        ],
        "cp": [
            cp("CP-022-01", "CA-01", "Lista sin aprendices", "Cero filas de censo"),
            cp("CP-022-02", "CA-02", "Inactivar y login", "HU-010 rechaza"),
            cp("CP-022-03", "CA-03", "Reasignar centro", "Opera el nuevo"),
            cp("CP-022-04", "CA-04", "Funcionario lista red", "403", "Permiso"),
        ],
        "riesgo": "Medio: mezclar padrones en la UI o dejar entrar inactivos.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-023-AD",
        "sheet": "HU-023-AD",
        "titulo": "Registrar un aprendiz por formulario (alta puntual)",
        "como": "Administrador",
        "quiero": "dar de alta a alguien que no vino en el Excel",
        "para": "incluirlo en el padrón con grupo, programa y centro",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-03 Censo",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-015",
        "feature_nom": "Alta puntual de aprendiz",
        "rf": "RF-NU-023",
        "cu": "CU-23",
        "journey": "J-04",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M. El Excel cubre el padrón masivo. Esto es el parche operativo.",
        "sp": 5,
        "sp_why": "Formulario con correo único, perfil Aprendiz, grupo/programa/centro. Jornada vive en el grupo (confirmar en RF).",
        "rank": 20,
        "fase": "E — Red / excepciones de padrón",
        "mvp": "No (el piloto se cubre con HU-012)",
        "valor": "No deja fuera a quien llegó tarde al Excel.",
        "problema": "Excepciones de matrícula. El riesgo: que el funcionario use esta API para cargar otra sede (el actor de la HU es el Administrador).",
        "exito": "Aprendiz con correo único, perfil Aprendiz, grupo, programa y centro. Jornada = la del grupo. Funcionario no usa esta vía como importación encubierta de otra sede.",
        "in_scope": [
            "Alta puntual por formulario",
            "Correo único",
            "Perfil Aprendiz",
            "Grupo, programa y centro",
        ],
        "out_scope": [
            "Import Excel (012/024)",
            "Que el funcionario dé altas de otra sede (P20: ¿también en su sede? abierto; hoy el actor es Admin)",
        ],
        "pre": "HU-010 admin. Catálogos de grupo/programa/centro.",
        "post": "El aprendiz puede entrar a urna (HU-001) si está habilitado.",
        "trigger": "Envía el formulario de alta.",
        "permisos_si": "Administrador.",
        "permisos_no": "Funcionario: no hay HU de alta puntual de otra sede. P20 pregunta si en SU sede. Hasta entonces, actor = Admin.",
        "entidades": "Aprendiz, Grupo, ProgramaFormacion, CentroFormacion, Perfil",
        "campos": "correo único · nombres/apellidos/documento · grupo · programa · centro · perfil Aprendiz. Jornada: en el grupo (escribirlo en RF).",
        "rn": "RN-SIG-017, RN-SIG-013",
        "rnf": "RNF-NU-001",
        "deps": "HU-010-GE",
        "bloquea": "Ninguna dura del MVP",
        "dueno": "Maicol",
        "dor": "Ready para especificar el alta de admin · P20 y jornada en RF",
        "dor_gap": "P20 ¿el funcionario también? Jornada: documentar que vive en el grupo.",
        "invest": "Cumple como alta de admin.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Correo duplicado = rechazo. Perfil resultante Aprendiz. Gate: funcionario no llama esta API para otra sede.",
        "notas_dev": "POST /api/aprendiz/crear + autorización de rol (hoy ⚠️ sin middleware). Jornada no como campo suelto contradictorio del grupo.",
        "preguntas": "P20 alta puntual por funcionario en su sede.",
        "tareas": "BE alta · unique correo · gate admin · FE form · tests",
        "ca": [
            ca("CA-01", "Feliz",
               "correo libre y grupo/programa/centro existentes",
               "el administrador da de alta",
               "queda un aprendiz de ese centro, perfil Aprendiz, jornada la de su grupo"),
            ca("CA-02", "Excepción",
               "correo ya usado",
               "envía",
               "se rechaza"),
            ca("CA-03", "Permiso",
               "esta vía",
               "la usa un funcionario para cargar OTRA sede",
               "no es el actor de la HU; se rechaza. P20 cubre si el funcionario puede en SU sede."),
        ],
        "ca_cond": [
            ca("CA-P20", "Condicionado",
               "el funcionario quiere un alta puntual en su propio centro",
               "usa un formulario",
               "no hay HU de funcionario. No se afirma que pueda ni que no 'en su sede' más allá de: esta HU es de Administrador."),
        ],
        "cp": [
            cp("CP-023-01", "CA-01", "Alta feliz", "Aprendiz en ese centro"),
            cp("CP-023-02", "CA-02", "Correo duplicado", "Rechazo", "Excepción"),
            cp("CP-023-03", "CA-03", "Funcionario a otra sede", "403", "Permiso"),
        ],
        "riesgo": "Medio: API abierta sin rol.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-024-AD",
        "sheet": "HU-024-AD",
        "titulo": "Importar el Excel eligiendo el centro destino",
        "como": "Administrador",
        "quiero": "importar la misma plantilla SENA eligiendo el centro",
        "para": "cargar el censo de cualquier sede sin usar la sesión de un funcionario",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-03 Censo",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-016",
        "feature_nom": "Importación eligiendo centro",
        "rf": "RF-NU-024",
        "cu": "CU-24",
        "journey": "J-04",
        "moscow": "MUST HAVE",
        "moscow_why": "Must de red. El piloto de UN centro puede vivir con HU-012. La red no puede: el admin no 'se loguea como funcionario de cada sede'.",
        "sp": 8,
        "sp_why": "Reutiliza parser de 012; cambia la regla de centro (obligatorio en request). NO fusionar con 012.",
        "rank": 15,
        "fase": "E — Red",
        "mvp": "No para el primer comicio de un centro (sí MUST cuando se opere red).",
        "valor": "Misma plantilla, otra regla de tenencia. RN-010.",
        "problema": "Fusionar 012 y 024: el funcionario terminaría eligiendo sede.",
        "exito": "Sin centroFormacionId no corre. Plantilla C2 + filas desde 5. Informe insertados/actualizados/omitidos. Funcionario no usa esta vía.",
        "in_scope": [
            "Import con centroFormacionId obligatorio",
            "Misma plantilla que HU-012 (C2, filas ≥5)",
            "Mismo tipo de informe",
            "Prohibido al funcionario",
        ],
        "out_scope": [
            "Import de funcionario (HU-012, centro = sesión)",
            "Combo de sedes en la mesa del funcionario",
        ],
        "pre": "HU-010 admin. Centro destino existente.",
        "post": "Padrón de ESA sede cargado. Cero uso por funcionario.",
        "trigger": "Admin sube Excel y elige centro.",
        "permisos_si": "Administrador.",
        "permisos_no": "Funcionario (RN-010). Aprendiz.",
        "entidades": "Aprendiz, Grupo, CentroFormacion",
        "campos": "archivo · centroFormacionId (obligatorio) · misma plantilla C2 / fila 5",
        "rn": "RN-SIG-010, RN-SIG-020, RN-SIG-013",
        "rnf": "RNF-NU-001",
        "deps": "HU-010-GE; parser de 012 (reutilizar, no copiar reglas de centro)",
        "bloquea": "Escala de red, no el piloto",
        "dueno": "Maicol",
        "dor": "Ready para especificar si se mantiene 012≠024",
        "dor_gap": "Ninguna de negocio si no se fusionan.",
        "invest": "Cumple SI no se fusiona con 012.",
        "invest_ok": "Cumple INVEST (no fusionar 012)",
        "notas_qa": "Sin centroFormacionId = 400. Funcionario = 403. Mismos contadores que 012. Un Excel no arrastra el centro de la sesión del admin: arrastra el elegido.",
        "notas_dev": "Endpoint distinto o flag de modo. Reusar parseo. NO reusar la regla de centro=sesión.",
        "preguntas": "Ninguna de plantilla. No fusionar.",
        "tareas": "BE import con centro obligatorio · 403 funcionario · reusar parser · tests",
        "ca": [
            ca("CA-01", "Feliz",
               "admin autenticado, centroFormacionId válido, Excel de plantilla",
               "importa",
               "el padrón queda en el centro ELEGIDO; informe de insertados/actualizados/omitidos"),
            ca("CA-02", "Validación",
               "falta centroFormacionId",
               "importa",
               "no corre (400)"),
            ca("CA-03", "Feliz",
               "se compara con HU-012",
               "se observa la regla de centro",
               "aquí se ELIGE; allá lo impone la sesión. Misma plantilla C2 / fila 5"),
            ca("CA-04", "Permiso",
               "un funcionario",
               "usa esta vía para otra sede",
               "se rechaza"),
        ],
        "ca_cond": [],
        "cp": [
            cp("CP-024-01", "CA-01", "Import con centro", "Padrón en destino; tres contadores"),
            cp("CP-024-02", "CA-02", "Sin centro", "400", "Validación"),
            cp("CP-024-03", "CA-04", "Funcionario", "403", "Permiso"),
            cp("CP-024-04", "CA-03", "Contraste con 012", "Reglas de centro distintas"),
        ],
        "riesgo": "Alto de producto si se fusiona con 012.",
        "estado": "Especificada",
    },
    {
        "id": "HU-SIG-025-AD",
        "sheet": "HU-025-AD",
        "titulo": "Consultar aprendices de la red o de un centro (sin contraseñas)",
        "como": "Administrador",
        "quiero": "buscar por centro, estado o texto",
        "para": "ubicar el censo SIN ver contraseñas ni hashes",
        "actor": "Administrador",
        "producto": "Red",
        "modulo": "M-03 Censo",
        "epica": "EP-SIG-005",
        "epica_nom": "Red institucional",
        "feature": "FT-SIG-017",
        "feature_nom": "Consulta de censo institucional",
        "rf": "RF-NU-025",
        "cu": "CU-25",
        "journey": "J-04",
        "moscow": "SHOULD HAVE",
        "moscow_why": "Prioridad M. Opera la red; no habilita el voto.",
        "sp": 3,
        "sp_why": "Consulta con filtros y serialize sin secretos.",
        "rank": 22,
        "fase": "E — Red",
        "mvp": "No",
        "valor": "RN-018. Encontrar a alguien en el padrón nacional sin filtrar secretos.",
        "problema": "Un GET de censo que trae hash. Un funcionario que ve toda la red (no es esta HU).",
        "exito": "Filtros centro / estado / texto. Body y columnas sin password ni hash. Actor = Administrador.",
        "in_scope": [
            "Búsqueda por centro, estado, texto",
            "Respuesta sin password ni hash",
        ],
        "out_scope": [
            "HU de funcionario consultando SOLO su centro (hay API aprendicesPorCentro; no hay HU — P11, no se crea aquí)",
            "Editar censo en masa",
        ],
        "pre": "HU-010 admin. Padrón con datos.",
        "post": "El admin ubicó personas. Cero secretos en el JSON.",
        "trigger": "Aplica filtros o busca texto.",
        "permisos_si": "Administrador.",
        "permisos_no": "Aprendiz. Funcionario: no esta HU (P11).",
        "entidades": "Aprendiz, CentroFormacion, Grupo",
        "campos": "filtros: centro, estado, texto. SALIDA: identidad de padrón. PROHIBIDO: password, hash.",
        "rn": "RN-SIG-018",
        "rnf": "RNF-NU-001",
        "deps": "HU-010-GE",
        "bloquea": "Ninguna",
        "dueno": "Maicol",
        "dor": "Ready para especificar consulta de admin",
        "dor_gap": "P11 listado de funcionario de su centro: no se agrega HU aquí.",
        "invest": "Cumple.",
        "invest_ok": "Cumple INVEST",
        "notas_qa": "Inspeccionar JSON y CSV/tabla: cero password. Filtros combinados. Funcionario no usa este endpoint de red.",
        "notas_dev": "GET censo con filtros. serializeAs null en password. No loguear hashes.",
        "preguntas": "P11 ¿funcionario lista padrón de su centro? Hay API, no HU.",
        "tareas": "BE filtros · strip password · FE búsqueda · tests de secreto",
        "ca": [
            ca("CA-01", "Feliz",
               "padrón con varios centros y estados",
               "el administrador filtra por centro, estado o texto",
               "obtiene coincidencias de esa búsqueda"),
            ca("CA-02", "Seguridad",
               "cualquier respuesta de esta consulta",
               "se inspecciona el JSON / la tabla",
               "no incluye contraseña ni hash"),
            ca("CA-03", "Permiso",
               "esta consulta de red",
               "la pide un aprendiz",
               "no se sirve"),
        ],
        "ca_cond": [
            ca("CA-P11", "Condicionado",
               "un funcionario quiere el padrón de SU centro",
               "usa un listado",
               "existe API por centro; NO hay HU. No se crea en este archivo. P11."),
        ],
        "cp": [
            cp("CP-025-01", "CA-01", "Filtro centro/estado/texto", "Resultados acotados"),
            cp("CP-025-02", "CA-02", "JSON sin password", "Cero secretos", "Seguridad"),
            cp("CP-025-03", "CA-03", "Aprendiz", "403", "Permiso"),
        ],
        "riesgo": "Alto de privacidad si el serialize falla.",
        "estado": "Especificada",
    },
]
